http://uui.upce.cz/perlgcache.cgi
http://dlaikar.de/cgi-bin/gcache2-cgi/gcache.cgi
http://mac.gc.dlaikar.de/ 
http://mitglied.lycos.de/monster954/gwebcache/gcache.php
http://dlaikar.de/gcache/gcache.php 
http://dlaikar.de/gcache-mac/gcache.php
http://gwc.nonamer.ath.cx:8080/
http://www.gwc2.ip3.com/cgi-bin/gwc2/gcache.cgi
http://www.gwc.freeola.com/cgi-bin/gwc/gcache.cgi
http://www.gbwebpro.com/guo/lynn/cache/lynn.asp
http://gwebcache.bearshare.net/
http://members.lycos.co.uk/malaycyber/gwcii.php
http://gcache.cloppy.net/
http://cache.warrink.ath.cx:8000/
http://crab.ghostwhitecrab.com/gwc/
http://gwebcache.bearshare.net/gcache.php
http://gwebcache1.limewire.com/gwebcache/cgi-bin/perlgcache.cgi
http://gwc1.nouiz.org/servlet/GWebCache/req32004051112241401
http://bobsmith-gwc.kicks-ass.org/
http://www.lostdaemon.net/gwebcache/gcache.php
http://loot.alumnigroup.org/
http://cache.mynapster.com/index.php
http://gcache.kccricket.net/cgi-bin/perlgcache.cgi
http://galvatron.dyndns.org:59009/gwcache
http://www.rodage.net/gnetcache/gcache.php
http://dlaikar.de/gcache2/gcache.php
http://bobsmith.is-a-geek.org/
http://jum.dyndns.org:9006/GWebCache/req
