#
# $Id$
#
# Bootstrapping file for the web cache.
#

http://bbs.robertwoolley.co.uk/GWebCache/gcache.php
http://binary.gamer.net.nz/gwebcache/gcache.php
http://bobsmith.kicks-ass.org/gwebcache/gcache.php
http://broneer.free.fr/gcache/gcache.php
http://cache.mynapster.com/index.php
http://cgi.verplant.org/octoGCache.pl
http://cmt.homeip.net/gwebcache-0.7.5/gcache.php
http://deftone.free.fr/elinul/gcache.php
http://diamond-host.com/gwebcache/gcache.php
http://ds.tranzision.com/cache/gcache.php
http://firebird.shacknet.nu:8888/cash.php
http://g2wc.markushenn.de/gwcii.php
http://gattinger.org/gcache/gcache.php
http://gcache.cloppy.net/
http://gcache.mikama.eu.org/
http://gcache.scottdial.com/gcache.php
http://grupaprojektor.host.sk/gcache.php
http://gwc-gruppo2003.homeip.net/gcache.php
http://gwc.fspn.cryptnet.net/gcache.cgi
http://gwc.gnewsgroups.com/cgi-bin/gcache.cgi
http://gwc.ionichost.com/gwc.php
http://gwc.nickstallman.net/gcache.asp
http://gwcii.julianfamily.org/gwcii.php
http://gwcii.thegistofit.net/
http://gwebcache.bearshare.net/gcache.php
http://gwebcache2.jonatkins.com/cgi-bin/gwebcache.cgi
http://gwebcache3.jonatkins.org.uk/perlgcache.cgi
http://herb.kicks-ass.net/gwebcache/
http://huithome.xs4all.nl/gwebcache/lynnx.aspx
http://invalidsubdomain.toddenrentieren.net/gcache.php
http://mckeowbc.servebeer.com/gcache.php
http://members.lycos.co.uk/coolebra/gwebcache-0.7.4/gcache.php
http://membres.lycos.fr/tium2000/gcache.php
http://mitglied.lycos.de/danacho/gwebcache/gcache.php
http://mitglied.lycos.de/h2flow/gwc/gcache.php
http://nocilla.boimorto.com/cgi-bin/gnocilla.pl
http://p2pdotcn.gotdns.org/pcache/pcache.php
http://pwc.fspn.cryptnet.net/cpwc.cgi
http://gcache.shacknet.nu:8088/gwc
http://r3dk0w.dyndns.org/gwebcache/gcache.php
http://tv2knet.basm.be/gcache.php
http://ui.upce.cz/~mirek/perlgcache.cgi
http://unknown.junkyjunk.com/cgi-bin/gwebcache/gcache.cgi
http://www.bearguru.com/gcache/gcache.asp
http://www.celeborn.dnsalias.org/gwebcache/gcache.php
http://www.diamond-host.com/gwebcache/gcache.php
http://www.easypublish.net/gwebcache/gcache.asp
http://www.edazzle.net/gerry/gerry.asp
http://www.gbwebpro.com/guo/lynn/cache/lynn.asp
http://www.gwc2.ip3.com/cgi-bin/gwc2/gcache.cgi
http://www.inthetrunk.com/gcache/gcache.php
http://www.lostdaemon.net/gwebcache/gcache.php
http://www.puxie.nl/gwebcache/gcache.php
http://www.rodage.net/gnetcache/gcache.php
http://www.spiderplayer.net/gwebcache.aspx
http://www.theholt.net/gcache.php
http://www.waddell.ch/cache
http://www.wtndrifters.com/gcache.php
http://www.xolox.nl/gwebcache/default.asp
http://www.yellowgoat.net/gwebcache/gcache.php
