#!/bin/sh

# This is where the configuration stuff is stored.
export GTK_GNUTELLA_DIR=$HOME/.gtk-gnutella

# turn on core dumps and delete old dump
ulimit -S -c unlimited
rm -f core

# run gtk-gnutella and start gdb on a core dump
src/gtk-gnutella 2> gtk-gnutella.warn | tee gtk-gnutella.log
if [ -e core ] ; then { 
    tail -3 gtk-gnutella.warn
    gdb src/gtk-gnutella core
} 
fi