#! /bin/sh -x
# $Id$
CACHE=$1
URL="$CACHE"'?hostfile=1&client=GTKG&version=0.93u'
LOGFILE=/tmp/gwccheck.log

{
	echo BEGIN: "$CACHE";
	echo;
	curl -Z 0 -s --connect-time 8 --max-time 15 -o /dev/stdout "$URL";
	echo; 
	echo END;
	echo; 
} >> "$LOGFILE"

