.TH GTK\-GNUTELLA 1 "July 06, 2001"
.SH NAME
gtk\-gnutella - share files in a peer to peer network
.SH SYNOPSIS
.B gtk\-gnutella
.SH "DESCRIPTION"
.B Gtk\-gnutella
is a graphical client for the Gnutella network. It features
searching and downloading shared files from other users, using
a simple, user-friendly GTK interface.
.PP
.B Gtk\-gnutella
takes no command-line options. Just run it and use the intuitive
graphical user interface.
.SH AUTHOR
This manual page was written by Andras Bali <bali@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
Gtk\-gnutella was written by Yann Grossel <olrick@users.sourceforge.net>.
