/*
 * Copyright (c) 2001-2002, Richard Eckart
 *
 * THIS FILE IS AUTOGENERATED! DO NOT EDIT!
 *
 *----------------------------------------------------------------------
 * This file is part of gtk-gnutella.
 *
 *  gtk-gnutella is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  gtk-gnutella is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with gtk-gnutella; if not, write to the Free Software
 *  Foundation, Inc.:
 *      59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *----------------------------------------------------------------------
 */

#include "prop.h"
#include "gnet_property_priv.h"
#include "gnet_property.h"


/*
 * Includes specified by "uses"-statement in .ag file
 */
#include "filter.h"
#include "sockets.h"
#include "gnet.h"



gboolean reading_hostfile     = FALSE;
gboolean reading_hostfile_def = FALSE;
gboolean ancient_version     = FALSE;
gboolean ancient_version_def = FALSE;
gchar   *new_version_str     = "no new version available";
gchar   *new_version_str_def = "no new version available";
guint32  up_connections     = 4;
guint32  up_connections_def = 4;
guint32  max_connections     = 4;
guint32  max_connections_def = 4;
guint32  max_downloads     = 10;
guint32  max_downloads_def = 10;
guint32  max_host_downloads     = 4;
guint32  max_host_downloads_def = 4;
guint32  max_uploads     = 5;
guint32  max_uploads_def = 5;
guint32  max_uploads_ip     = 2;
guint32  max_uploads_ip_def = 2;
guint32  local_ip     = 0x00000000;
guint32  local_ip_def = 0x00000000;
guint32  listen_port     = 6436;
guint32  listen_port_def = 6436;
guint32  forced_local_ip     = 0x00000000;
guint32  forced_local_ip_def = 0x00000000;
guint32  minimum_speed     = 0;
guint32  minimum_speed_def = 0;
guint32  connection_speed     = 0;
guint32  connection_speed_def = 0;
guint32  search_max_items     = 50;
guint32  search_max_items_def = 50;
guint32  ul_usage_min_percentage     = 70;
guint32  ul_usage_min_percentage_def = 70;
guint32  download_connecting_timeout     = 30;
guint32  download_connecting_timeout_def = 30;
guint32  download_push_sent_timeout     = 60;
guint32  download_push_sent_timeout_def = 60;
guint32  download_connected_timeout     = 60;
guint32  download_connected_timeout_def = 60;
guint32  download_retry_timeout_min     = 20;
guint32  download_retry_timeout_min_def = 20;
guint32  download_retry_timeout_max     = 120;
guint32  download_retry_timeout_max_def = 120;
guint32  download_max_retries     = 256;
guint32  download_max_retries_def = 256;
guint32  download_retry_timeout_delay     = 1200;
guint32  download_retry_timeout_delay_def = 1200;
guint32  download_retry_busy_delay     = 60;
guint32  download_retry_busy_delay_def = 60;
guint32  download_retry_refused_delay     = 1800;
guint32  download_retry_refused_delay_def = 1800;
guint32  download_retry_stopped_delay     = 15;
guint32  download_retry_stopped_delay_def = 15;
guint32  download_overlap_range     = 512;
guint32  download_overlap_range_def = 512;
guint32  upload_connecting_timeout     = 60;
guint32  upload_connecting_timeout_def = 60;
guint32  upload_connected_timeout     = 180;
guint32  upload_connected_timeout_def = 180;
guint32  search_reissue_timeout     = 600;
guint32  search_reissue_timeout_def = 600;
guint32  ban_ratio_fds     = 25;
guint32  ban_ratio_fds_def = 25;
guint32  ban_max_fds     = 100;
guint32  ban_max_fds_def = 100;
guint32  node_connecting_timeout     = 5;
guint32  node_connecting_timeout_def = 5;
guint32  node_connected_timeout     = 45;
guint32  node_connected_timeout_def = 45;
guint32  node_sendqueue_size     = 98304;
guint32  node_sendqueue_size_def = 98304;
guint32  node_tx_flowc_timeout     = 60;
guint32  node_tx_flowc_timeout_def = 60;
guint32  max_ttl     = 10;
guint32  max_ttl_def = 10;
guint32  my_ttl     = 7;
guint32  my_ttl_def = 7;
guint32  hard_ttl_limit     = 10;
guint32  hard_ttl_limit_def = 10;
guint32  dbg     = 0;
guint32  dbg_def = 0;
gboolean stop_host_get     = FALSE;
gboolean stop_host_get_def = FALSE;
guint32  filter_default_policy     = FILTER_PROP_STATE_DO;
guint32  filter_default_policy_def = FILTER_PROP_STATE_DO;
gboolean bws_in_enabled     = FALSE;
gboolean bws_in_enabled_def = FALSE;
gboolean bws_out_enabled     = FALSE;
gboolean bws_out_enabled_def = FALSE;
gboolean bws_gin_enabled     = FALSE;
gboolean bws_gin_enabled_def = FALSE;
gboolean bws_gout_enabled     = FALSE;
gboolean bws_gout_enabled_def = FALSE;
gboolean bw_ul_usage_enabled     = TRUE;
gboolean bw_ul_usage_enabled_def = TRUE;
gboolean clear_uploads     = FALSE;
gboolean clear_uploads_def = FALSE;
gboolean clear_downloads     = FALSE;
gboolean clear_downloads_def = FALSE;
gboolean search_remove_downloaded     = FALSE;
gboolean search_remove_downloaded_def = FALSE;
gboolean force_local_ip     = FALSE;
gboolean force_local_ip_def = FALSE;
gboolean use_netmasks     = TRUE;
gboolean use_netmasks_def = TRUE;
gboolean download_delete_aborted     = TRUE;
gboolean download_delete_aborted_def = TRUE;
gboolean proxy_connections     = FALSE;
gboolean proxy_connections_def = FALSE;
gboolean proxy_auth     = FALSE;
gboolean proxy_auth_def = FALSE;
gchar   *socks_user     = "username";
gchar   *socks_user_def = "username";
gchar   *socks_pass     = "password";
gchar   *socks_pass_def = "password";
guint32  proxy_ip     = 0x00000000;
guint32  proxy_ip_def = 0x00000000;
guint32  proxy_port     = 0x0000;
guint32  proxy_port_def = 0x0000;
guint32  proxy_protocol     = PROXY_SOCKSV4;
guint32  proxy_protocol_def = PROXY_SOCKSV4;
guint32  max_hosts_cached     = 20480;
guint32  max_hosts_cached_def = 20480;
guint32  hosts_in_catcher     = 0;
guint32  hosts_in_catcher_def = 0;
guint32  max_high_ttl_msg     = 10;
guint32  max_high_ttl_msg_def = 10;
guint32  max_high_ttl_radius     = 2;
guint32  max_high_ttl_radius_def = 2;
guint32  bw_http_in     = 0;
guint32  bw_http_in_def = 0;
guint32  bw_http_out     = 0;
guint32  bw_http_out_def = 0;
guint32  bw_gnet_in     = 0;
guint32  bw_gnet_in_def = 0;
guint32  bw_gnet_out     = 0;
guint32  bw_gnet_out_def = 0;
guint32  search_queries_forward_size     = 256;
guint32  search_queries_forward_size_def = 256;
guint32  search_queries_kick_size     = 1024;
guint32  search_queries_kick_size_def = 1024;
guint32  search_answers_forward_size     = 65536;
guint32  search_answers_forward_size_def = 65536;
guint32  search_answers_kick_size     = 65536;
guint32  search_answers_kick_size_def = 65536;
guint32  other_messages_kick_size     = 40960;
guint32  other_messages_kick_size_def = 40960;
guint32  hops_random_factor     = 0;
guint32  hops_random_factor_def = 0;
gboolean send_pushes     = TRUE;
gboolean send_pushes_def = TRUE;
guint32  min_dup_msg     = 5;
guint32  min_dup_msg_def = 5;
guint32  min_dup_ratio     = 1;
guint32  min_dup_ratio_def = 1;
gchar   *scan_extensions     = "asf;avi;bz2;divx;gif;gz;it;jpeg;jpg;mod;mov;mpg;mpeg;mp3;mp2;mp1;ogg;png;ps;pdf;rar;s3m;stm;txt;voc;vqf;wav;wma;xm;zip";
gchar   *scan_extensions_def = "asf;avi;bz2;divx;gif;gz;it;jpeg;jpg;mod;mov;mpg;mpeg;mp3;mp2;mp1;ogg;png;ps;pdf;rar;s3m;stm;txt;voc;vqf;wav;wma;xm;zip";
gchar   *save_file_path     = "/tmp";
gchar   *save_file_path_def = "/tmp";
gchar   *move_file_path     = ".";
gchar   *move_file_path_def = ".";
gchar   *shared_dirs_paths     = "";
gchar   *shared_dirs_paths_def = "";
gchar   *local_netmasks_string     = "";
gchar   *local_netmasks_string_def = "";
gboolean search_stats_enabled     = FALSE;
gboolean search_stats_enabled_def = FALSE;
guint32  search_stats_update_interval     = 200;
guint32  search_stats_update_interval_def = 200;
guint32  search_stats_delcoef     = 25;
guint32  search_stats_delcoef_def = 25;
guint32  total_downloads     = 0;
guint32  total_downloads_def = 0;
guint32  total_uploads     = 0;
guint32  total_uploads_def = 0;
guint8   guid[16];

static prop_set_t *gnet_property = NULL;

prop_set_t *gnet_prop_init(void) {
    gnet_property = g_new(prop_set_t, 1);
    gnet_property->name   = "gnet_property";
    gnet_property->desc   = "";
    gnet_property->size   = GNET_PROPERTY_NUM;
    gnet_property->offset = 0;
    gnet_property->mtime  = 0;
    gnet_property->props  = g_new(prop_def_t, GNET_PROPERTY_NUM);
    gnet_property->get_stub = gnet_prop_get_stub;


    /*
     * PROP_READING_HOSTFILE:
     *
     * General data:
     */
    gnet_property->props[0].name = "reading_hostfile";
    gnet_property->props[0].desc = "Indicates wether the hostcache file is being read";
    gnet_property->props[0].prop_changed_listeners = NULL;
    gnet_property->props[0].save = FALSE;
    gnet_property->props[0].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[0].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[0].data.boolean.def   = &reading_hostfile_def;
    gnet_property->props[0].data.boolean.value = &reading_hostfile;


    /*
     * PROP_ANCIENT_VERSION:
     *
     * General data:
     */
    gnet_property->props[1].name = "ancient_version";
    gnet_property->props[1].desc = "Indicates that gtk-gnutella finds the version you run very very old";
    gnet_property->props[1].prop_changed_listeners = NULL;
    gnet_property->props[1].save = FALSE;
    gnet_property->props[1].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[1].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[1].data.boolean.def   = &ancient_version_def;
    gnet_property->props[1].data.boolean.value = &ancient_version;


    /*
     * PROP_NEW_VERSION_STR:
     *
     * General data:
     */
    gnet_property->props[2].name = "new_version_str";
    gnet_property->props[2].desc = "Gtk-gnutella found a newer version on the gNet and givesinformation about it here";
    gnet_property->props[2].prop_changed_listeners = NULL;
    gnet_property->props[2].save = FALSE;
    gnet_property->props[2].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[2].type               = PROP_TYPE_STRING;
    gnet_property->props[2].data.string.def    = &new_version_str_def;
    gnet_property->props[2].data.string.value  = &new_version_str;
    *gnet_property->props[2].data.string.value =
        g_strdup(*gnet_property->props[2].data.string.def);


    /*
     * PROP_UP_CONNECTIONS:
     *
     * General data:
     */
    gnet_property->props[3].name = "up_connections";
    gnet_property->props[3].desc = "Try to keep at least this number of connections to otherservents";
    gnet_property->props[3].prop_changed_listeners = NULL;
    gnet_property->props[3].save = TRUE;
    gnet_property->props[3].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[3].type               = PROP_TYPE_GUINT32;
    gnet_property->props[3].data.guint32.def   = &up_connections_def;
    gnet_property->props[3].data.guint32.value = &up_connections;
    gnet_property->props[3].data.guint32.max   = 100;
    gnet_property->props[3].data.guint32.min   = 1;


    /*
     * PROP_MAX_CONNECTIONS:
     *
     * General data:
     */
    gnet_property->props[4].name = "max_connections";
    gnet_property->props[4].desc = "Don't allow more that this number of connections to otherservents";
    gnet_property->props[4].prop_changed_listeners = NULL;
    gnet_property->props[4].save = TRUE;
    gnet_property->props[4].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[4].type               = PROP_TYPE_GUINT32;
    gnet_property->props[4].data.guint32.def   = &max_connections_def;
    gnet_property->props[4].data.guint32.value = &max_connections;
    gnet_property->props[4].data.guint32.max   = 100;
    gnet_property->props[4].data.guint32.min   = 0;


    /*
     * PROP_MAX_DOWNLOADS:
     *
     * General data:
     */
    gnet_property->props[5].name = "max_simultaneous_downloads";
    gnet_property->props[5].desc = "Don't start more than this number of parallel downloads";
    gnet_property->props[5].prop_changed_listeners = NULL;
    gnet_property->props[5].save = TRUE;
    gnet_property->props[5].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[5].type               = PROP_TYPE_GUINT32;
    gnet_property->props[5].data.guint32.def   = &max_downloads_def;
    gnet_property->props[5].data.guint32.value = &max_downloads;
    gnet_property->props[5].data.guint32.max   = 100;
    gnet_property->props[5].data.guint32.min   = 0;


    /*
     * PROP_MAX_HOST_DOWNLOADS:
     *
     * General data:
     */
    gnet_property->props[6].name = "max_simultaneous_host_downloads";
    gnet_property->props[6].desc = "Don't make more connections then given here to a single host to download a file";
    gnet_property->props[6].prop_changed_listeners = NULL;
    gnet_property->props[6].save = TRUE;
    gnet_property->props[6].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[6].type               = PROP_TYPE_GUINT32;
    gnet_property->props[6].data.guint32.def   = &max_host_downloads_def;
    gnet_property->props[6].data.guint32.value = &max_host_downloads;
    gnet_property->props[6].data.guint32.max   = 100;
    gnet_property->props[6].data.guint32.min   = 1;


    /*
     * PROP_MAX_UPLOADS:
     *
     * General data:
     */
    gnet_property->props[7].name = "max_simultaneous_uploads";
    gnet_property->props[7].desc = "Don't allow more then this number of uploads in total";
    gnet_property->props[7].prop_changed_listeners = NULL;
    gnet_property->props[7].save = TRUE;
    gnet_property->props[7].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[7].type               = PROP_TYPE_GUINT32;
    gnet_property->props[7].data.guint32.def   = &max_uploads_def;
    gnet_property->props[7].data.guint32.value = &max_uploads;
    gnet_property->props[7].data.guint32.max   = 100;
    gnet_property->props[7].data.guint32.min   = 0;


    /*
     * PROP_MAX_UPLOADS_IP:
     *
     * General data:
     */
    gnet_property->props[8].name = "max_uploads_ip";
    gnet_property->props[8].desc = "Don't upload more then this number of files in parallel to a single host";
    gnet_property->props[8].prop_changed_listeners = NULL;
    gnet_property->props[8].save = TRUE;
    gnet_property->props[8].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[8].type               = PROP_TYPE_GUINT32;
    gnet_property->props[8].data.guint32.def   = &max_uploads_ip_def;
    gnet_property->props[8].data.guint32.value = &max_uploads_ip;
    gnet_property->props[8].data.guint32.max   = 100;
    gnet_property->props[8].data.guint32.min   = 1;


    /*
     * PROP_LOCAL_IP:
     *
     * General data:
     */
    gnet_property->props[9].name = "local_ip";
    gnet_property->props[9].desc = "Local IP address";
    gnet_property->props[9].prop_changed_listeners = NULL;
    gnet_property->props[9].save = FALSE;
    gnet_property->props[9].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[9].type               = PROP_TYPE_IP;
    gnet_property->props[9].data.guint32.def   = &local_ip_def;
    gnet_property->props[9].data.guint32.value = &local_ip;
    gnet_property->props[9].data.guint32.max   = 0xFFFFFFFF;
    gnet_property->props[9].data.guint32.min   = 0x00000000;


    /*
     * PROP_LISTEN_PORT:
     *
     * General data:
     */
    gnet_property->props[10].name = "listen_port";
    gnet_property->props[10].desc = "Local port gtk-gnutella is listening on";
    gnet_property->props[10].prop_changed_listeners = NULL;
    gnet_property->props[10].save = TRUE;
    gnet_property->props[10].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[10].type               = PROP_TYPE_GUINT32;
    gnet_property->props[10].data.guint32.def   = &listen_port_def;
    gnet_property->props[10].data.guint32.value = &listen_port;
    gnet_property->props[10].data.guint32.max   = 0xFFFF;
    gnet_property->props[10].data.guint32.min   = 0x0000;


    /*
     * PROP_FORCED_LOCAL_IP:
     *
     * General data:
     */
    gnet_property->props[11].name = "forced_local_ip";
    gnet_property->props[11].desc = "Use this IP address as source address if 'force local ip' is activated";
    gnet_property->props[11].prop_changed_listeners = NULL;
    gnet_property->props[11].save = TRUE;
    gnet_property->props[11].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[11].type               = PROP_TYPE_IP;
    gnet_property->props[11].data.guint32.def   = &forced_local_ip_def;
    gnet_property->props[11].data.guint32.value = &forced_local_ip;
    gnet_property->props[11].data.guint32.max   = 0xFFFFFFFF;
    gnet_property->props[11].data.guint32.min   = 0x00000000;


    /*
     * PROP_MINIMUM_SPEED:
     *
     * General data:
     */
    gnet_property->props[12].name = "search_minimum_speed";
    gnet_property->props[12].desc = "This is the default minimum speed for new searches in kbit/s";
    gnet_property->props[12].prop_changed_listeners = NULL;
    gnet_property->props[12].save = TRUE;
    gnet_property->props[12].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[12].type               = PROP_TYPE_GUINT32;
    gnet_property->props[12].data.guint32.def   = &minimum_speed_def;
    gnet_property->props[12].data.guint32.value = &minimum_speed;
    gnet_property->props[12].data.guint32.max   = 2000;
    gnet_property->props[12].data.guint32.min   = 0;


    /*
     * PROP_CONNECTION_SPEED:
     *
     * General data:
     */
    gnet_property->props[13].name = "connection_speed";
    gnet_property->props[13].desc = "The connection bandwidth reported to other hosts";
    gnet_property->props[13].prop_changed_listeners = NULL;
    gnet_property->props[13].save = TRUE;
    gnet_property->props[13].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[13].type               = PROP_TYPE_GUINT32;
    gnet_property->props[13].data.guint32.def   = &connection_speed_def;
    gnet_property->props[13].data.guint32.value = &connection_speed;
    gnet_property->props[13].data.guint32.max   = 2000;
    gnet_property->props[13].data.guint32.min   = 0;


    /*
     * PROP_QUERY_RESPONSE_MAX_ITEMS:
     *
     * General data:
     */
    gnet_property->props[14].name = "limit_search_results";
    gnet_property->props[14].desc = "Return at most this number of results in a query response";
    gnet_property->props[14].prop_changed_listeners = NULL;
    gnet_property->props[14].save = TRUE;
    gnet_property->props[14].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[14].type               = PROP_TYPE_GUINT32;
    gnet_property->props[14].data.guint32.def   = &search_max_items_def;
    gnet_property->props[14].data.guint32.value = &search_max_items;
    gnet_property->props[14].data.guint32.max   = 255;
    gnet_property->props[14].data.guint32.min   = 1;


    /*
     * PROP_UL_USAGE_MIN_PERCENTAGE:
     *
     * General data:
     */
    gnet_property->props[15].name = "upload_bandwith_min_percentage";
    gnet_property->props[15].desc = "Unless this percentage or more of the upload bandwidth is used, allow additional upload slots";
    gnet_property->props[15].prop_changed_listeners = NULL;
    gnet_property->props[15].save = TRUE;
    gnet_property->props[15].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[15].type               = PROP_TYPE_GUINT32;
    gnet_property->props[15].data.guint32.def   = &ul_usage_min_percentage_def;
    gnet_property->props[15].data.guint32.value = &ul_usage_min_percentage;
    gnet_property->props[15].data.guint32.max   = 100;
    gnet_property->props[15].data.guint32.min   = 0;


    /*
     * PROP_DOWNLOAD_CONNECTING_TIMEOUT:
     *
     * General data:
     */
    gnet_property->props[16].name = "download_connecting_timeout";
    gnet_property->props[16].desc = "Number of seconds before a download connect attempt times out";
    gnet_property->props[16].prop_changed_listeners = NULL;
    gnet_property->props[16].save = TRUE;
    gnet_property->props[16].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[16].type               = PROP_TYPE_GUINT32;
    gnet_property->props[16].data.guint32.def   = &download_connecting_timeout_def;
    gnet_property->props[16].data.guint32.value = &download_connecting_timeout;
    gnet_property->props[16].data.guint32.max   = 100000;
    gnet_property->props[16].data.guint32.min   = 1;


    /*
     * PROP_DOWNLOAD_PUSH_SENT_TIMEOUT:
     *
     * General data:
     */
    gnet_property->props[17].name = "download_push_sent_timeout";
    gnet_property->props[17].desc = "Number of seconds before a push request times out";
    gnet_property->props[17].prop_changed_listeners = NULL;
    gnet_property->props[17].save = TRUE;
    gnet_property->props[17].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[17].type               = PROP_TYPE_GUINT32;
    gnet_property->props[17].data.guint32.def   = &download_push_sent_timeout_def;
    gnet_property->props[17].data.guint32.value = &download_push_sent_timeout;
    gnet_property->props[17].data.guint32.max   = 100000;
    gnet_property->props[17].data.guint32.min   = 1;


    /*
     * PROP_DOWNLOAD_CONNECTED_TIMEOUT:
     *
     * General data:
     */
    gnet_property->props[18].name = "download_connected_timeout";
    gnet_property->props[18].desc = "Number of seconds before a download times out if no data is recieved";
    gnet_property->props[18].prop_changed_listeners = NULL;
    gnet_property->props[18].save = TRUE;
    gnet_property->props[18].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[18].type               = PROP_TYPE_GUINT32;
    gnet_property->props[18].data.guint32.def   = &download_connected_timeout_def;
    gnet_property->props[18].data.guint32.value = &download_connected_timeout;
    gnet_property->props[18].data.guint32.max   = 100000;
    gnet_property->props[18].data.guint32.min   = 1;


    /*
     * PROP_DOWNLOAD_RETRY_TIMEOUT_MIN:
     *
     * General data:
     */
    gnet_property->props[19].name = "download_retry_timeout_min";
    gnet_property->props[19].desc = "Minimum number of seconds to wait on auto-retry timeouts";
    gnet_property->props[19].prop_changed_listeners = NULL;
    gnet_property->props[19].save = TRUE;
    gnet_property->props[19].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[19].type               = PROP_TYPE_GUINT32;
    gnet_property->props[19].data.guint32.def   = &download_retry_timeout_min_def;
    gnet_property->props[19].data.guint32.value = &download_retry_timeout_min;
    gnet_property->props[19].data.guint32.max   = 100000;
    gnet_property->props[19].data.guint32.min   = 1;


    /*
     * PROP_DOWNLOAD_RETRY_TIMEOUT_MAX:
     *
     * General data:
     */
    gnet_property->props[20].name = "download_retry_timeout_max";
    gnet_property->props[20].desc = "Maximum number of seconds to wait on auto-retry timeouts";
    gnet_property->props[20].prop_changed_listeners = NULL;
    gnet_property->props[20].save = TRUE;
    gnet_property->props[20].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[20].type               = PROP_TYPE_GUINT32;
    gnet_property->props[20].data.guint32.def   = &download_retry_timeout_max_def;
    gnet_property->props[20].data.guint32.value = &download_retry_timeout_max;
    gnet_property->props[20].data.guint32.max   = 100000;
    gnet_property->props[20].data.guint32.min   = 1;


    /*
     * PROP_DOWNLOAD_MAX_RETRIES:
     *
     * General data:
     */
    gnet_property->props[21].name = "download_max_retries";
    gnet_property->props[21].desc = "Maximum number of attempts to download a file not counting HTTP busy indications";
    gnet_property->props[21].prop_changed_listeners = NULL;
    gnet_property->props[21].save = TRUE;
    gnet_property->props[21].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[21].type               = PROP_TYPE_GUINT32;
    gnet_property->props[21].data.guint32.def   = &download_max_retries_def;
    gnet_property->props[21].data.guint32.value = &download_max_retries;
    gnet_property->props[21].data.guint32.max   = 100000;
    gnet_property->props[21].data.guint32.min   = 1;


    /*
     * PROP_DOWNLOAD_RETRY_TIMEOUT_DELAY:
     *
     * General data:
     */
    gnet_property->props[22].name = "download_retry_timeout_delay";
    gnet_property->props[22].desc = "Delay in seconds before retrying after a connection timed out";
    gnet_property->props[22].prop_changed_listeners = NULL;
    gnet_property->props[22].save = TRUE;
    gnet_property->props[22].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[22].type               = PROP_TYPE_GUINT32;
    gnet_property->props[22].data.guint32.def   = &download_retry_timeout_delay_def;
    gnet_property->props[22].data.guint32.value = &download_retry_timeout_delay;
    gnet_property->props[22].data.guint32.max   = 100000;
    gnet_property->props[22].data.guint32.min   = 15;


    /*
     * PROP_DOWNLOAD_RETRY_BUSY_DELAY:
     *
     * General data:
     */
    gnet_property->props[23].name = "download_retry_busy_delay";
    gnet_property->props[23].desc = "Delay in seconds before retrying after getting a 'busy' response from a host";
    gnet_property->props[23].prop_changed_listeners = NULL;
    gnet_property->props[23].save = TRUE;
    gnet_property->props[23].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[23].type               = PROP_TYPE_GUINT32;
    gnet_property->props[23].data.guint32.def   = &download_retry_busy_delay_def;
    gnet_property->props[23].data.guint32.value = &download_retry_busy_delay;
    gnet_property->props[23].data.guint32.max   = 100000;
    gnet_property->props[23].data.guint32.min   = 15;


    /*
     * PROP_DOWNLOAD_RETRY_REFUSED_DELAY:
     *
     * General data:
     */
    gnet_property->props[24].name = "download_retry_refused_delay";
    gnet_property->props[24].desc = "Delay in seconds before retrying after getting a 'connection refused' response from a host";
    gnet_property->props[24].prop_changed_listeners = NULL;
    gnet_property->props[24].save = TRUE;
    gnet_property->props[24].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[24].type               = PROP_TYPE_GUINT32;
    gnet_property->props[24].data.guint32.def   = &download_retry_refused_delay_def;
    gnet_property->props[24].data.guint32.value = &download_retry_refused_delay;
    gnet_property->props[24].data.guint32.max   = 100000;
    gnet_property->props[24].data.guint32.min   = 15;


    /*
     * PROP_DOWNLOAD_RETRY_STOPPED_DELAY:
     *
     * General data:
     */
    gnet_property->props[25].name = "download_retry_stopped";
    gnet_property->props[25].desc = "Delay in seconds before retrying after a retry stopped (timed out, connection reset by peer, etc.)";
    gnet_property->props[25].prop_changed_listeners = NULL;
    gnet_property->props[25].save = TRUE;
    gnet_property->props[25].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[25].type               = PROP_TYPE_GUINT32;
    gnet_property->props[25].data.guint32.def   = &download_retry_stopped_delay_def;
    gnet_property->props[25].data.guint32.value = &download_retry_stopped_delay;
    gnet_property->props[25].data.guint32.max   = 100000;
    gnet_property->props[25].data.guint32.min   = 15;


    /*
     * PROP_DOWNLOAD_OVERLAP_RANGE:
     *
     * General data:
     */
    gnet_property->props[26].name = "download_overlap_range";
    gnet_property->props[26].desc = "Ammount of bytes to overlap when resuming a download";
    gnet_property->props[26].prop_changed_listeners = NULL;
    gnet_property->props[26].save = TRUE;
    gnet_property->props[26].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[26].type               = PROP_TYPE_GUINT32;
    gnet_property->props[26].data.guint32.def   = &download_overlap_range_def;
    gnet_property->props[26].data.guint32.value = &download_overlap_range;
    gnet_property->props[26].data.guint32.max   = SOCK_BUFSZ;
    gnet_property->props[26].data.guint32.min   = 1;


    /*
     * PROP_UPLOAD_CONNECTING_TIMEOUT:
     *
     * General data:
     */
    gnet_property->props[27].name = "upload_connecting_timeout";
    gnet_property->props[27].desc = "Number of seconds before an upload times out if no connection can be established during a push";
    gnet_property->props[27].prop_changed_listeners = NULL;
    gnet_property->props[27].save = TRUE;
    gnet_property->props[27].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[27].type               = PROP_TYPE_GUINT32;
    gnet_property->props[27].data.guint32.def   = &upload_connecting_timeout_def;
    gnet_property->props[27].data.guint32.value = &upload_connecting_timeout;
    gnet_property->props[27].data.guint32.max   = 100000;
    gnet_property->props[27].data.guint32.min   = 1;


    /*
     * PROP_UPLOAD_CONNECTED_TIMEOUT:
     *
     * General data:
     */
    gnet_property->props[28].name = "upload_connected_timeout";
    gnet_property->props[28].desc = "Number of seconds before an upload times out if no data is transmitted";
    gnet_property->props[28].prop_changed_listeners = NULL;
    gnet_property->props[28].save = TRUE;
    gnet_property->props[28].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[28].type               = PROP_TYPE_GUINT32;
    gnet_property->props[28].data.guint32.def   = &upload_connected_timeout_def;
    gnet_property->props[28].data.guint32.value = &upload_connected_timeout;
    gnet_property->props[28].data.guint32.max   = 100000;
    gnet_property->props[28].data.guint32.min   = 1;


    /*
     * PROP_SEARCH_REISSUE_TIMEOUT:
     *
     * General data:
     */
    gnet_property->props[29].name = "search_reissue_timeout";
    gnet_property->props[29].desc = "Ammount of seconds to wait before a search is issued again to see if new results are available";
    gnet_property->props[29].prop_changed_listeners = NULL;
    gnet_property->props[29].save = TRUE;
    gnet_property->props[29].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[29].type               = PROP_TYPE_GUINT32;
    gnet_property->props[29].data.guint32.def   = &search_reissue_timeout_def;
    gnet_property->props[29].data.guint32.value = &search_reissue_timeout;
    gnet_property->props[29].data.guint32.max   = 9999;
    gnet_property->props[29].data.guint32.min   = 600;


    /*
     * PROP_BAN_RATIO_FDS:
     *
     * General data:
     */
    gnet_property->props[30].name = "ban_ratio_fds";
    gnet_property->props[30].desc = "Maximum ratio of file descriptors reserved for banning";
    gnet_property->props[30].prop_changed_listeners = NULL;
    gnet_property->props[30].save = TRUE;
    gnet_property->props[30].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[30].type               = PROP_TYPE_GUINT32;
    gnet_property->props[30].data.guint32.def   = &ban_ratio_fds_def;
    gnet_property->props[30].data.guint32.value = &ban_ratio_fds;
    gnet_property->props[30].data.guint32.max   = 100;
    gnet_property->props[30].data.guint32.min   = 0;


    /*
     * PROP_BAN_MAX_FDS:
     *
     * General data:
     */
    gnet_property->props[31].name = "ban_max_fds";
    gnet_property->props[31].desc = "Maximum number of file descriptors reserved for banning";
    gnet_property->props[31].prop_changed_listeners = NULL;
    gnet_property->props[31].save = TRUE;
    gnet_property->props[31].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[31].type               = PROP_TYPE_GUINT32;
    gnet_property->props[31].data.guint32.def   = &ban_max_fds_def;
    gnet_property->props[31].data.guint32.value = &ban_max_fds;
    gnet_property->props[31].data.guint32.max   = 10000;
    gnet_property->props[31].data.guint32.min   = 0;


    /*
     * PROP_NODE_CONNECTING_TIMEOUT:
     *
     * General data:
     */
    gnet_property->props[32].name = "node_connecting_timeout";
    gnet_property->props[32].desc = "Number of seconds before a gNet connect attempt times out if no connection can be established";
    gnet_property->props[32].prop_changed_listeners = NULL;
    gnet_property->props[32].save = TRUE;
    gnet_property->props[32].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[32].type               = PROP_TYPE_GUINT32;
    gnet_property->props[32].data.guint32.def   = &node_connecting_timeout_def;
    gnet_property->props[32].data.guint32.value = &node_connecting_timeout;
    gnet_property->props[32].data.guint32.max   = 100000;
    gnet_property->props[32].data.guint32.min   = 1;


    /*
     * PROP_NODE_CONNECTED_TIMEOUT:
     *
     * General data:
     */
    gnet_property->props[33].name = "node_connected_timeout";
    gnet_property->props[33].desc = "Number of seconds before a gNet connection times out if no data is transmitted";
    gnet_property->props[33].prop_changed_listeners = NULL;
    gnet_property->props[33].save = TRUE;
    gnet_property->props[33].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[33].type               = PROP_TYPE_GUINT32;
    gnet_property->props[33].data.guint32.def   = &node_connected_timeout_def;
    gnet_property->props[33].data.guint32.value = &node_connected_timeout;
    gnet_property->props[33].data.guint32.max   = 100000;
    gnet_property->props[33].data.guint32.min   = 1;


    /*
     * PROP_NODE_SENDQUEUE_SIZE:
     *
     * General data:
     */
    gnet_property->props[34].name = "node_sendqueue_size";
    gnet_property->props[34].desc = "Maximum size of the sendqueue for the nodes (in bytes). Must be at lest 150% of the maximum message size";
    gnet_property->props[34].prop_changed_listeners = NULL;
    gnet_property->props[34].save = TRUE;
    gnet_property->props[34].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[34].type               = PROP_TYPE_GUINT32;
    gnet_property->props[34].data.guint32.def   = &node_sendqueue_size_def;
    gnet_property->props[34].data.guint32.value = &node_sendqueue_size;
    gnet_property->props[34].data.guint32.max   = 256000;
    gnet_property->props[34].data.guint32.min   = 98305;


    /*
     * PROP_NODE_TX_FLOWC_TIMEOUT:
     *
     * General data:
     */
    gnet_property->props[35].name = "node_tx_flowc_timeout";
    gnet_property->props[35].desc = "Maximum number of seconds a node can remain in transit flow control";
    gnet_property->props[35].prop_changed_listeners = NULL;
    gnet_property->props[35].save = TRUE;
    gnet_property->props[35].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[35].type               = PROP_TYPE_GUINT32;
    gnet_property->props[35].data.guint32.def   = &node_tx_flowc_timeout_def;
    gnet_property->props[35].data.guint32.value = &node_tx_flowc_timeout;
    gnet_property->props[35].data.guint32.max   = 100000;
    gnet_property->props[35].data.guint32.min   = 1;


    /*
     * PROP_MAX_TTL:
     *
     * General data:
     */
    gnet_property->props[36].name = "max_ttl";
    gnet_property->props[36].desc = "[unknown, please provide description in gnet_props.ag]";
    gnet_property->props[36].prop_changed_listeners = NULL;
    gnet_property->props[36].save = TRUE;
    gnet_property->props[36].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[36].type               = PROP_TYPE_GUINT32;
    gnet_property->props[36].data.guint32.def   = &max_ttl_def;
    gnet_property->props[36].data.guint32.value = &max_ttl;
    gnet_property->props[36].data.guint32.max   = 99;
    gnet_property->props[36].data.guint32.min   = 1;


    /*
     * PROP_MY_TTL:
     *
     * General data:
     */
    gnet_property->props[37].name = "my_ttl";
    gnet_property->props[37].desc = "[unknown, please provide description in gnet_props.ag]";
    gnet_property->props[37].prop_changed_listeners = NULL;
    gnet_property->props[37].save = TRUE;
    gnet_property->props[37].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[37].type               = PROP_TYPE_GUINT32;
    gnet_property->props[37].data.guint32.def   = &my_ttl_def;
    gnet_property->props[37].data.guint32.value = &my_ttl;
    gnet_property->props[37].data.guint32.max   = 99;
    gnet_property->props[37].data.guint32.min   = 1;


    /*
     * PROP_HARD_TTL_LIMIT:
     *
     * General data:
     */
    gnet_property->props[38].name = "hard_ttl_limit";
    gnet_property->props[38].desc = "Maximum hard TTL limit (hop+ttl) on message";
    gnet_property->props[38].prop_changed_listeners = NULL;
    gnet_property->props[38].save = TRUE;
    gnet_property->props[38].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[38].type               = PROP_TYPE_GUINT32;
    gnet_property->props[38].data.guint32.def   = &hard_ttl_limit_def;
    gnet_property->props[38].data.guint32.value = &hard_ttl_limit;
    gnet_property->props[38].data.guint32.max   = 99;
    gnet_property->props[38].data.guint32.min   = 1;


    /*
     * PROP_DBG:
     *
     * General data:
     */
    gnet_property->props[39].name = "dbg";
    gnet_property->props[39].desc = "For development use: debug level";
    gnet_property->props[39].prop_changed_listeners = NULL;
    gnet_property->props[39].save = TRUE;
    gnet_property->props[39].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[39].type               = PROP_TYPE_GUINT32;
    gnet_property->props[39].data.guint32.def   = &dbg_def;
    gnet_property->props[39].data.guint32.value = &dbg;
    gnet_property->props[39].data.guint32.max   = 20;
    gnet_property->props[39].data.guint32.min   = 0;


    /*
     * PROP_STOP_HOST_GET:
     *
     * General data:
     */
    gnet_property->props[40].name = "stop_host_get";
    gnet_property->props[40].desc = "For development use: don't add new hosts to the hostcatcher";
    gnet_property->props[40].prop_changed_listeners = NULL;
    gnet_property->props[40].save = TRUE;
    gnet_property->props[40].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[40].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[40].data.boolean.def   = &stop_host_get_def;
    gnet_property->props[40].data.boolean.value = &stop_host_get;


    /*
     * PROP_FILTER_DEFAULT_POLICY:
     *
     * General data:
     */
    gnet_property->props[41].name = "filter_default_policy";
    gnet_property->props[41].desc = "Default policy for the DISPLAY filter property";
    gnet_property->props[41].prop_changed_listeners = NULL;
    gnet_property->props[41].save = TRUE;
    gnet_property->props[41].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[41].type               = PROP_TYPE_GUINT32;
    gnet_property->props[41].data.guint32.def   = &filter_default_policy_def;
    gnet_property->props[41].data.guint32.value = &filter_default_policy;
    gnet_property->props[41].data.guint32.max   = FILTER_PROP_STATE_DONT;
    gnet_property->props[41].data.guint32.min   = FILTER_PROP_STATE_DO;


    /*
     * PROP_BW_HTTP_IN_ENABLED:
     *
     * General data:
     */
    gnet_property->props[42].name = "bandwidth_input_limit";
    gnet_property->props[42].desc = "Enable bandwidth limitation for incoming HTTP traffic";
    gnet_property->props[42].prop_changed_listeners = NULL;
    gnet_property->props[42].save = TRUE;
    gnet_property->props[42].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[42].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[42].data.boolean.def   = &bws_in_enabled_def;
    gnet_property->props[42].data.boolean.value = &bws_in_enabled;


    /*
     * PROP_BW_HTTP_OUT_ENABLED:
     *
     * General data:
     */
    gnet_property->props[43].name = "bandwidth_output_limit";
    gnet_property->props[43].desc = "Enable bandwidth limitation for outgoing HTTP traffic";
    gnet_property->props[43].prop_changed_listeners = NULL;
    gnet_property->props[43].save = TRUE;
    gnet_property->props[43].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[43].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[43].data.boolean.def   = &bws_out_enabled_def;
    gnet_property->props[43].data.boolean.value = &bws_out_enabled;


    /*
     * PROP_BW_GNET_IN_ENABLED:
     *
     * General data:
     */
    gnet_property->props[44].name = "bandwidth_ginput_limit";
    gnet_property->props[44].desc = "Enable bandwidth limitation for incoming gNet traffic";
    gnet_property->props[44].prop_changed_listeners = NULL;
    gnet_property->props[44].save = TRUE;
    gnet_property->props[44].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[44].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[44].data.boolean.def   = &bws_gin_enabled_def;
    gnet_property->props[44].data.boolean.value = &bws_gin_enabled;


    /*
     * PROP_BW_GNET_OUT_ENABLED:
     *
     * General data:
     */
    gnet_property->props[45].name = "bandwidth_goutput_limit";
    gnet_property->props[45].desc = "Enable bandwidth limitation for outgoing gNet traffic";
    gnet_property->props[45].prop_changed_listeners = NULL;
    gnet_property->props[45].save = TRUE;
    gnet_property->props[45].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[45].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[45].data.boolean.def   = &bws_gout_enabled_def;
    gnet_property->props[45].data.boolean.value = &bws_gout_enabled;


    /*
     * PROP_BW_UL_USAGE_ENABLED:
     *
     * General data:
     */
    gnet_property->props[46].name = "upload_bandwith_usage_enabled";
    gnet_property->props[46].desc = "Enable dynamic upload slots allocation";
    gnet_property->props[46].prop_changed_listeners = NULL;
    gnet_property->props[46].save = TRUE;
    gnet_property->props[46].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[46].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[46].data.boolean.def   = &bw_ul_usage_enabled_def;
    gnet_property->props[46].data.boolean.value = &bw_ul_usage_enabled;


    /*
     * PROP_AUTOCLEAR_UPLOADS:
     *
     * General data:
     */
    gnet_property->props[47].name = "auto_clear_completed_uploads";
    gnet_property->props[47].desc = "Auto clear completed uploads";
    gnet_property->props[47].prop_changed_listeners = NULL;
    gnet_property->props[47].save = TRUE;
    gnet_property->props[47].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[47].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[47].data.boolean.def   = &clear_uploads_def;
    gnet_property->props[47].data.boolean.value = &clear_uploads;


    /*
     * PROP_AUTOCLEAR_DOWNLOADS:
     *
     * General data:
     */
    gnet_property->props[48].name = "auto_clear_completed_downloads";
    gnet_property->props[48].desc = "Auto clear completed downloads";
    gnet_property->props[48].prop_changed_listeners = NULL;
    gnet_property->props[48].save = TRUE;
    gnet_property->props[48].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[48].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[48].data.boolean.def   = &clear_downloads_def;
    gnet_property->props[48].data.boolean.value = &clear_downloads;


    /*
     * PROP_SEARCH_REMOVE_DOWNLOADED:
     *
     * General data:
     */
    gnet_property->props[49].name = "search_remove_downloaded";
    gnet_property->props[49].desc = "Remove downloaded files from the search result";
    gnet_property->props[49].prop_changed_listeners = NULL;
    gnet_property->props[49].save = TRUE;
    gnet_property->props[49].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[49].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[49].data.boolean.def   = &search_remove_downloaded_def;
    gnet_property->props[49].data.boolean.value = &search_remove_downloaded;


    /*
     * PROP_FORCE_LOCAL_IP:
     *
     * General data:
     */
    gnet_property->props[50].name = "force_local_ip";
    gnet_property->props[50].desc = "Enable to use [forced_local_ip] as local ip";
    gnet_property->props[50].prop_changed_listeners = NULL;
    gnet_property->props[50].save = TRUE;
    gnet_property->props[50].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[50].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[50].data.boolean.def   = &force_local_ip_def;
    gnet_property->props[50].data.boolean.value = &force_local_ip;


    /*
     * PROP_USE_NETMASKS:
     *
     * General data:
     */
    gnet_property->props[51].name = "use_netmasks";
    gnet_property->props[51].desc = "Try to connect to local networks first";
    gnet_property->props[51].prop_changed_listeners = NULL;
    gnet_property->props[51].save = TRUE;
    gnet_property->props[51].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[51].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[51].data.boolean.def   = &use_netmasks_def;
    gnet_property->props[51].data.boolean.value = &use_netmasks;


    /*
     * PROP_DOWNLOAD_DELETE_ABORTED:
     *
     * General data:
     */
    gnet_property->props[52].name = "download_delete_aborted";
    gnet_property->props[52].desc = "Remove files of aborted downloads from disk";
    gnet_property->props[52].prop_changed_listeners = NULL;
    gnet_property->props[52].save = TRUE;
    gnet_property->props[52].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[52].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[52].data.boolean.def   = &download_delete_aborted_def;
    gnet_property->props[52].data.boolean.value = &download_delete_aborted;


    /*
     * PROP_PROXY_CONNECTIONS:
     *
     * General data:
     */
    gnet_property->props[53].name = "proxy_connections";
    gnet_property->props[53].desc = "Use a proxy to connect to the internet";
    gnet_property->props[53].prop_changed_listeners = NULL;
    gnet_property->props[53].save = TRUE;
    gnet_property->props[53].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[53].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[53].data.boolean.def   = &proxy_connections_def;
    gnet_property->props[53].data.boolean.value = &proxy_connections;


    /*
     * PROP_PROXY_AUTH:
     *
     * General data:
     */
    gnet_property->props[54].name = "proxy_auth";
    gnet_property->props[54].desc = "Use username and password to authenticate to proxy";
    gnet_property->props[54].prop_changed_listeners = NULL;
    gnet_property->props[54].save = TRUE;
    gnet_property->props[54].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[54].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[54].data.boolean.def   = &proxy_auth_def;
    gnet_property->props[54].data.boolean.value = &proxy_auth;


    /*
     * PROP_SOCKS_USER:
     *
     * General data:
     */
    gnet_property->props[55].name = "socks_user";
    gnet_property->props[55].desc = "Username for proxy";
    gnet_property->props[55].prop_changed_listeners = NULL;
    gnet_property->props[55].save = TRUE;
    gnet_property->props[55].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[55].type               = PROP_TYPE_STRING;
    gnet_property->props[55].data.string.def    = &socks_user_def;
    gnet_property->props[55].data.string.value  = &socks_user;
    *gnet_property->props[55].data.string.value =
        g_strdup(*gnet_property->props[55].data.string.def);


    /*
     * PROP_SOCKS_PASS:
     *
     * General data:
     */
    gnet_property->props[56].name = "socks_pass";
    gnet_property->props[56].desc = "Password for proxy";
    gnet_property->props[56].prop_changed_listeners = NULL;
    gnet_property->props[56].save = TRUE;
    gnet_property->props[56].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[56].type               = PROP_TYPE_STRING;
    gnet_property->props[56].data.string.def    = &socks_pass_def;
    gnet_property->props[56].data.string.value  = &socks_pass;
    *gnet_property->props[56].data.string.value =
        g_strdup(*gnet_property->props[56].data.string.def);


    /*
     * PROP_PROXY_IP:
     *
     * General data:
     */
    gnet_property->props[57].name = "proxy_ip";
    gnet_property->props[57].desc = "IP address of the proxy";
    gnet_property->props[57].prop_changed_listeners = NULL;
    gnet_property->props[57].save = TRUE;
    gnet_property->props[57].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[57].type               = PROP_TYPE_IP;
    gnet_property->props[57].data.guint32.def   = &proxy_ip_def;
    gnet_property->props[57].data.guint32.value = &proxy_ip;
    gnet_property->props[57].data.guint32.max   = 0xFFFFFFFF;
    gnet_property->props[57].data.guint32.min   = 0x00000000;


    /*
     * PROP_PROXY_PORT:
     *
     * General data:
     */
    gnet_property->props[58].name = "proxy_port";
    gnet_property->props[58].desc = "Port the proxy is listening on";
    gnet_property->props[58].prop_changed_listeners = NULL;
    gnet_property->props[58].save = TRUE;
    gnet_property->props[58].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[58].type               = PROP_TYPE_GUINT32;
    gnet_property->props[58].data.guint32.def   = &proxy_port_def;
    gnet_property->props[58].data.guint32.value = &proxy_port;
    gnet_property->props[58].data.guint32.max   = 0xFFFF;
    gnet_property->props[58].data.guint32.min   = 0x0000;


    /*
     * PROP_PROXY_PROTOCOL:
     *
     * General data:
     */
    gnet_property->props[59].name = "proxy_protocol";
    gnet_property->props[59].desc = "Protocol the proxy uses";
    gnet_property->props[59].prop_changed_listeners = NULL;
    gnet_property->props[59].save = TRUE;
    gnet_property->props[59].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[59].type               = PROP_TYPE_GUINT32;
    gnet_property->props[59].data.guint32.def   = &proxy_protocol_def;
    gnet_property->props[59].data.guint32.value = &proxy_protocol;
    gnet_property->props[59].data.guint32.max   = 0x5;
    gnet_property->props[59].data.guint32.min   = 0x1;


    /*
     * PROP_MAX_HOSTS_CACHED:
     *
     * General data:
     */
    gnet_property->props[60].name = "max_hosts_cached";
    gnet_property->props[60].desc = "Maximum number of hosts in the host catcher";
    gnet_property->props[60].prop_changed_listeners = NULL;
    gnet_property->props[60].save = TRUE;
    gnet_property->props[60].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[60].type               = PROP_TYPE_GUINT32;
    gnet_property->props[60].data.guint32.def   = &max_hosts_cached_def;
    gnet_property->props[60].data.guint32.value = &max_hosts_cached;
    gnet_property->props[60].data.guint32.max   = 100000;
    gnet_property->props[60].data.guint32.min   = 100;


    /*
     * PROP_HOSTS_IN_CATCHER:
     *
     * General data:
     */
    gnet_property->props[61].name = "hosts_in_catcher";
    gnet_property->props[61].desc = "Current number of hosts in hostcatcher";
    gnet_property->props[61].prop_changed_listeners = NULL;
    gnet_property->props[61].save = FALSE;
    gnet_property->props[61].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[61].type               = PROP_TYPE_GUINT32;
    gnet_property->props[61].data.guint32.def   = &hosts_in_catcher_def;
    gnet_property->props[61].data.guint32.value = &hosts_in_catcher;
    gnet_property->props[61].data.guint32.max   = 100000;
    gnet_property->props[61].data.guint32.min   = 0;


    /*
     * PROP_MAX_HIGH_TTL_MSG:
     *
     * General data:
     */
    gnet_property->props[62].name = "max_high_ttl_msg";
    gnet_property->props[62].desc = "Amount of tolerable messages abot hard TTL limit per node. See also MAX_HIGH_TTL_RADIUS";
    gnet_property->props[62].prop_changed_listeners = NULL;
    gnet_property->props[62].save = TRUE;
    gnet_property->props[62].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[62].type               = PROP_TYPE_GUINT32;
    gnet_property->props[62].data.guint32.def   = &max_high_ttl_msg_def;
    gnet_property->props[62].data.guint32.value = &max_high_ttl_msg;
    gnet_property->props[62].data.guint32.max   = 99;
    gnet_property->props[62].data.guint32.min   = 0;


    /*
     * PROP_MAX_HIGH_TTL_RADIUS:
     *
     * General data:
     */
    gnet_property->props[63].name = "max_high_ttl_radius";
    gnet_property->props[63].desc = "Hop radius for counting high TTL limit messages (# hops lower than...) See also MAX_HIGH_TTL_MSG";
    gnet_property->props[63].prop_changed_listeners = NULL;
    gnet_property->props[63].save = TRUE;
    gnet_property->props[63].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[63].type               = PROP_TYPE_GUINT32;
    gnet_property->props[63].data.guint32.def   = &max_high_ttl_radius_def;
    gnet_property->props[63].data.guint32.value = &max_high_ttl_radius;
    gnet_property->props[63].data.guint32.max   = 99;
    gnet_property->props[63].data.guint32.min   = 0;


    /*
     * PROP_BW_HTTP_IN:
     *
     * General data:
     */
    gnet_property->props[64].name = "input_bandwidth";
    gnet_property->props[64].desc = "Bandwidth limit for incoming HTTP traffic in bytes/sec";
    gnet_property->props[64].prop_changed_listeners = NULL;
    gnet_property->props[64].save = TRUE;
    gnet_property->props[64].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[64].type               = PROP_TYPE_GUINT32;
    gnet_property->props[64].data.guint32.def   = &bw_http_in_def;
    gnet_property->props[64].data.guint32.value = &bw_http_in;
    gnet_property->props[64].data.guint32.max   = BS_BW_MAX;
    gnet_property->props[64].data.guint32.min   = 0;


    /*
     * PROP_BW_HTTP_OUT:
     *
     * General data:
     */
    gnet_property->props[65].name = "output_bandwidth";
    gnet_property->props[65].desc = "Bandwidth limit for outgoing HTTP traffic in bytes/sec";
    gnet_property->props[65].prop_changed_listeners = NULL;
    gnet_property->props[65].save = TRUE;
    gnet_property->props[65].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[65].type               = PROP_TYPE_GUINT32;
    gnet_property->props[65].data.guint32.def   = &bw_http_out_def;
    gnet_property->props[65].data.guint32.value = &bw_http_out;
    gnet_property->props[65].data.guint32.max   = BS_BW_MAX;
    gnet_property->props[65].data.guint32.min   = 0;


    /*
     * PROP_BW_GNET_IN:
     *
     * General data:
     */
    gnet_property->props[66].name = "input_gnet_bandwidth";
    gnet_property->props[66].desc = "Bandwidth limit for incoming gNet traffic in bytes/sec";
    gnet_property->props[66].prop_changed_listeners = NULL;
    gnet_property->props[66].save = TRUE;
    gnet_property->props[66].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[66].type               = PROP_TYPE_GUINT32;
    gnet_property->props[66].data.guint32.def   = &bw_gnet_in_def;
    gnet_property->props[66].data.guint32.value = &bw_gnet_in;
    gnet_property->props[66].data.guint32.max   = BS_BW_MAX;
    gnet_property->props[66].data.guint32.min   = 0;


    /*
     * PROP_BW_GNET_OUT:
     *
     * General data:
     */
    gnet_property->props[67].name = "output_gnet_bandwidth";
    gnet_property->props[67].desc = "Bandwidth limit for outgoing gNet traffic in bytes/sec";
    gnet_property->props[67].prop_changed_listeners = NULL;
    gnet_property->props[67].save = TRUE;
    gnet_property->props[67].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[67].type               = PROP_TYPE_GUINT32;
    gnet_property->props[67].data.guint32.def   = &bw_gnet_out_def;
    gnet_property->props[67].data.guint32.value = &bw_gnet_out;
    gnet_property->props[67].data.guint32.max   = BS_BW_MAX;
    gnet_property->props[67].data.guint32.min   = 0;


    /*
     * PROP_SEARCH_QUERIES_FORWARD_SIZE:
     *
     * General data:
     */
    gnet_property->props[68].name = "search_queries_forward_size";
    gnet_property->props[68].desc = "Maximum size of search queries messages we forward to others  (in bytes)";
    gnet_property->props[68].prop_changed_listeners = NULL;
    gnet_property->props[68].save = TRUE;
    gnet_property->props[68].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[68].type               = PROP_TYPE_GUINT32;
    gnet_property->props[68].data.guint32.def   = &search_queries_forward_size_def;
    gnet_property->props[68].data.guint32.value = &search_queries_forward_size;
    gnet_property->props[68].data.guint32.max   = 65534;
    gnet_property->props[68].data.guint32.min   = 65;


    /*
     * PROP_SEARCH_QUERIES_KICK_SIZE:
     *
     * General data:
     */
    gnet_property->props[69].name = "search_queries_kick_size";
    gnet_property->props[69].desc = "Maximum size of search queries messages we allow, otherwise close the connection (in bytes)";
    gnet_property->props[69].prop_changed_listeners = NULL;
    gnet_property->props[69].save = TRUE;
    gnet_property->props[69].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[69].type               = PROP_TYPE_GUINT32;
    gnet_property->props[69].data.guint32.def   = &search_queries_kick_size_def;
    gnet_property->props[69].data.guint32.value = &search_queries_kick_size;
    gnet_property->props[69].data.guint32.max   = 65534;
    gnet_property->props[69].data.guint32.min   = 513;


    /*
     * PROP_SEARCH_ANSWERS_FORWARD_SIZE:
     *
     * General data:
     */
    gnet_property->props[70].name = "search_answers_forward_size";
    gnet_property->props[70].desc = "Maximum size of search answers messages we forward to others (in bytes)";
    gnet_property->props[70].prop_changed_listeners = NULL;
    gnet_property->props[70].save = TRUE;
    gnet_property->props[70].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[70].type               = PROP_TYPE_GUINT32;
    gnet_property->props[70].data.guint32.def   = &search_answers_forward_size_def;
    gnet_property->props[70].data.guint32.value = &search_answers_forward_size;
    gnet_property->props[70].data.guint32.max   = 1048575;
    gnet_property->props[70].data.guint32.min   = 513;


    /*
     * PROP_SEARCH_ANSWERS_KICK_SIZE:
     *
     * General data:
     */
    gnet_property->props[71].name = "search_answers_kick_size";
    gnet_property->props[71].desc = "Maximum size of search answers messages we allow, otherwise close the connection (in bytes)";
    gnet_property->props[71].prop_changed_listeners = NULL;
    gnet_property->props[71].save = TRUE;
    gnet_property->props[71].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[71].type               = PROP_TYPE_GUINT32;
    gnet_property->props[71].data.guint32.def   = &search_answers_kick_size_def;
    gnet_property->props[71].data.guint32.value = &search_answers_kick_size;
    gnet_property->props[71].data.guint32.max   = 1048575;
    gnet_property->props[71].data.guint32.min   = 513;


    /*
     * PROP_OTHER_MESSAGES_KICK_SIZE:
     *
     * General data:
     */
    gnet_property->props[72].name = "other_messages_kick_size";
    gnet_property->props[72].desc = "Maximum size of unknown messages we allow, otherwise close theconnection (in bytes)";
    gnet_property->props[72].prop_changed_listeners = NULL;
    gnet_property->props[72].save = TRUE;
    gnet_property->props[72].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[72].type               = PROP_TYPE_GUINT32;
    gnet_property->props[72].data.guint32.def   = &other_messages_kick_size_def;
    gnet_property->props[72].data.guint32.value = &other_messages_kick_size;
    gnet_property->props[72].data.guint32.max   = 1048575;
    gnet_property->props[72].data.guint32.min   = 513;


    /*
     * PROP_HOPS_RANDOM_FACTOR:
     *
     * General data:
     */
    gnet_property->props[73].name = "hops_random_factor";
    gnet_property->props[73].desc = "Random factor for the hops field in search packets we send between 0 and 3 inclusive)";
    gnet_property->props[73].prop_changed_listeners = NULL;
    gnet_property->props[73].save = TRUE;
    gnet_property->props[73].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[73].type               = PROP_TYPE_GUINT32;
    gnet_property->props[73].data.guint32.def   = &hops_random_factor_def;
    gnet_property->props[73].data.guint32.value = &hops_random_factor;
    gnet_property->props[73].data.guint32.max   = 3;
    gnet_property->props[73].data.guint32.min   = 0;


    /*
     * PROP_SEND_PUSHES:
     *
     * General data:
     */
    gnet_property->props[74].name = "send_pushes";
    gnet_property->props[74].desc = "Wether or not to send push requests";
    gnet_property->props[74].prop_changed_listeners = NULL;
    gnet_property->props[74].save = TRUE;
    gnet_property->props[74].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[74].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[74].data.boolean.def   = &send_pushes_def;
    gnet_property->props[74].data.boolean.value = &send_pushes;


    /*
     * PROP_MIN_DUP_MSG:
     *
     * General data:
     */
    gnet_property->props[75].name = "min_dup_msg";
    gnet_property->props[75].desc = "Minimum amount of dup messages to enable kicking, per node (also see [min_dup_ratio])";
    gnet_property->props[75].prop_changed_listeners = NULL;
    gnet_property->props[75].save = TRUE;
    gnet_property->props[75].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[75].type               = PROP_TYPE_GUINT32;
    gnet_property->props[75].data.guint32.def   = &min_dup_msg_def;
    gnet_property->props[75].data.guint32.value = &min_dup_msg;
    gnet_property->props[75].data.guint32.max   = 99;
    gnet_property->props[75].data.guint32.min   = 1;


    /*
     * PROP_MIN_DUP_RATIO:
     *
     * General data:
     */
    gnet_property->props[76].name = "min_dup_ratio";
    gnet_property->props[76].desc = "Minimum ratio of dups on received messages, per node (between 0.0 and 100.0) (also see [min_dup_msg])";
    gnet_property->props[76].prop_changed_listeners = NULL;
    gnet_property->props[76].save = TRUE;
    gnet_property->props[76].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[76].type               = PROP_TYPE_GUINT32;
    gnet_property->props[76].data.guint32.def   = &min_dup_ratio_def;
    gnet_property->props[76].data.guint32.value = &min_dup_ratio;
    gnet_property->props[76].data.guint32.max   = 100;
    gnet_property->props[76].data.guint32.min   = 0;


    /*
     * PROP_SCAN_EXTENSIONS:
     *
     * General data:
     */
    gnet_property->props[77].name = "shared_files_extensions";
    gnet_property->props[77].desc = "Only files with the given extensions will be shared";
    gnet_property->props[77].prop_changed_listeners = NULL;
    gnet_property->props[77].save = TRUE;
    gnet_property->props[77].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[77].type               = PROP_TYPE_STRING;
    gnet_property->props[77].data.string.def    = &scan_extensions_def;
    gnet_property->props[77].data.string.value  = &scan_extensions;
    *gnet_property->props[77].data.string.value =
        g_strdup(*gnet_property->props[77].data.string.def);


    /*
     * PROP_SAVE_FILE_PATH:
     *
     * General data:
     */
    gnet_property->props[78].name = "store_downloading_files_to";
    gnet_property->props[78].desc = "Store incomplete files in this directory";
    gnet_property->props[78].prop_changed_listeners = NULL;
    gnet_property->props[78].save = TRUE;
    gnet_property->props[78].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[78].type               = PROP_TYPE_STRING;
    gnet_property->props[78].data.string.def    = &save_file_path_def;
    gnet_property->props[78].data.string.value  = &save_file_path;
    *gnet_property->props[78].data.string.value =
        g_strdup(*gnet_property->props[78].data.string.def);


    /*
     * PROP_MOVE_FILE_PATH:
     *
     * General data:
     */
    gnet_property->props[79].name = "move_downloading_files_to";
    gnet_property->props[79].desc = "Move complete files to this directory";
    gnet_property->props[79].prop_changed_listeners = NULL;
    gnet_property->props[79].save = TRUE;
    gnet_property->props[79].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[79].type               = PROP_TYPE_STRING;
    gnet_property->props[79].data.string.def    = &move_file_path_def;
    gnet_property->props[79].data.string.value  = &move_file_path;
    *gnet_property->props[79].data.string.value =
        g_strdup(*gnet_property->props[79].data.string.def);


    /*
     * PROP_SHARED_DIRS_PATHS:
     *
     * General data:
     */
    gnet_property->props[80].name = "shared_dirs";
    gnet_property->props[80].desc = "Directories which contain shared files";
    gnet_property->props[80].prop_changed_listeners = NULL;
    gnet_property->props[80].save = TRUE;
    gnet_property->props[80].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[80].type               = PROP_TYPE_STRING;
    gnet_property->props[80].data.string.def    = &shared_dirs_paths_def;
    gnet_property->props[80].data.string.value  = &shared_dirs_paths;
    *gnet_property->props[80].data.string.value =
        g_strdup(*gnet_property->props[80].data.string.def);


    /*
     * PROP_LOCAL_NETMASKS_STRING:
     *
     * General data:
     */
    gnet_property->props[81].name = "local_netmasks";
    gnet_property->props[81].desc = "List of networks considered local";
    gnet_property->props[81].prop_changed_listeners = NULL;
    gnet_property->props[81].save = TRUE;
    gnet_property->props[81].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[81].type               = PROP_TYPE_STRING;
    gnet_property->props[81].data.string.def    = &local_netmasks_string_def;
    gnet_property->props[81].data.string.value  = &local_netmasks_string;
    *gnet_property->props[81].data.string.value =
        g_strdup(*gnet_property->props[81].data.string.def);


    /*
     * PROP_SEARCH_STATS_ENABLED:
     *
     * General data:
     */
    gnet_property->props[82].name = "search_stats_enabled";
    gnet_property->props[82].desc = "Collect statistics about search that go through this node";
    gnet_property->props[82].prop_changed_listeners = NULL;
    gnet_property->props[82].save = TRUE;
    gnet_property->props[82].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[82].type               = PROP_TYPE_BOOLEAN;
    gnet_property->props[82].data.boolean.def   = &search_stats_enabled_def;
    gnet_property->props[82].data.boolean.value = &search_stats_enabled;


    /*
     * PROP_SEARCH_STATS_UPDATE_INTERVAL:
     *
     * General data:
     */
    gnet_property->props[83].name = "search_stats_update_interval";
    gnet_property->props[83].desc = "Interval in which the search stats are updated";
    gnet_property->props[83].prop_changed_listeners = NULL;
    gnet_property->props[83].save = TRUE;
    gnet_property->props[83].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[83].type               = PROP_TYPE_GUINT32;
    gnet_property->props[83].data.guint32.def   = &search_stats_update_interval_def;
    gnet_property->props[83].data.guint32.value = &search_stats_update_interval;
    gnet_property->props[83].data.guint32.max   = 50000;
    gnet_property->props[83].data.guint32.min   = 0;


    /*
     * PROP_SEARCH_STATS_DELCOEF:
     *
     * General data:
     */
    gnet_property->props[84].name = "search_stats_delcoef";
    gnet_property->props[84].desc = "[unknown, please provide description in gnet_props.ag]";
    gnet_property->props[84].prop_changed_listeners = NULL;
    gnet_property->props[84].save = TRUE;
    gnet_property->props[84].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[84].type               = PROP_TYPE_GUINT32;
    gnet_property->props[84].data.guint32.def   = &search_stats_delcoef_def;
    gnet_property->props[84].data.guint32.value = &search_stats_delcoef;
    gnet_property->props[84].data.guint32.max   = 100;
    gnet_property->props[84].data.guint32.min   = 0;


    /*
     * PROP_TOTAL_DOWNLOADS:
     *
     * General data:
     */
    gnet_property->props[85].name = "total_downloads";
    gnet_property->props[85].desc = "Total number of completed downloads in this session";
    gnet_property->props[85].prop_changed_listeners = NULL;
    gnet_property->props[85].save = FALSE;
    gnet_property->props[85].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[85].type               = PROP_TYPE_GUINT32;
    gnet_property->props[85].data.guint32.def   = &total_downloads_def;
    gnet_property->props[85].data.guint32.value = &total_downloads;
    gnet_property->props[85].data.guint32.max   = 0xFFFFFFFF;
    gnet_property->props[85].data.guint32.min   = 0x00000000;


    /*
     * PROP_TOTAL_UPLOADS:
     *
     * General data:
     */
    gnet_property->props[86].name = "total_uploads";
    gnet_property->props[86].desc = "Total number of completed uploads in this session";
    gnet_property->props[86].prop_changed_listeners = NULL;
    gnet_property->props[86].save = FALSE;
    gnet_property->props[86].vector_size = 1;

    /* Type specific data: */
    gnet_property->props[86].type               = PROP_TYPE_GUINT32;
    gnet_property->props[86].data.guint32.def   = &total_uploads_def;
    gnet_property->props[86].data.guint32.value = &total_uploads;
    gnet_property->props[86].data.guint32.max   = 0xFFFFFFFF;
    gnet_property->props[86].data.guint32.min   = 0x00000000;


    /*
     * PROP_GUID:
     *
     * General data:
     */
    gnet_property->props[87].name = "guid";
    gnet_property->props[87].desc = "Global Unique IDentifier of this node";
    gnet_property->props[87].prop_changed_listeners = NULL;
    gnet_property->props[87].save = TRUE;
    gnet_property->props[87].vector_size = 16;

    /* Type specific data: */
    gnet_property->props[87].type               = PROP_TYPE_STORAGE;
    gnet_property->props[87].data.storage.value = guid;
    memset(guid, 0, gnet_property->props[87].vector_size);
    return gnet_property;
}

/*
 * gnet_prop_shutdown:
 *
 * Free memory allocated by the property set.
 */
void gnet_prop_shutdown(void) {
    gint n;

    for (n = 0; n < GNET_PROPERTY_NUM; n ++) {
        if (gnet_property->props[n].type == PROP_TYPE_STRING) {
            g_free(*gnet_property->props[n].data.string.value);
            *gnet_property->props[n].data.string.value = NULL;
        }
    }

    g_free(gnet_property->props);
    g_free(gnet_property);
}

prop_def_t *gnet_prop_get_def(property_t p)
{
    return prop_get_def(gnet_property, p);
}

/*
 * gnet_prop_add_prop_changed_listener:
 *
 * Add a change listener to a given property. If init is TRUE then
 * the listener is immediately called.
 */
void gnet_prop_add_prop_changed_listener
    (property_t prop, prop_changed_listener_t l, gboolean init)
{
    prop_add_prop_changed_listener(gnet_property, prop, l, init);
}

void gnet_prop_remove_prop_changed_listener
    (property_t prop, prop_changed_listener_t l)
{
    prop_remove_prop_changed_listener(gnet_property, prop, l);
}

void gnet_prop_set_boolean
    (property_t prop, const gboolean *src, gsize offset, gsize length)
{
    prop_set_boolean(gnet_property, prop, src, offset, length);
}

gboolean *gnet_prop_get_boolean
    (property_t prop, gboolean *t, gsize offset, gsize length)
{
    return prop_get_boolean(gnet_property, prop, t, offset, length);
}

void gnet_prop_set_guint32
    (property_t prop, const guint32 *src, gsize offset, gsize length)
{
    prop_set_guint32(gnet_property, prop, src, offset, length);
}

guint32 *gnet_prop_get_guint32
    (property_t prop, guint32 *t, gsize offset, gsize length)
{
    return prop_get_guint32(gnet_property, prop, t, offset, length);
}

void gnet_prop_set_string(property_t prop, const gchar *val)
{
    prop_set_string(gnet_property, prop, val);
}

gchar *gnet_prop_get_string(property_t prop, gchar *t, gsize size)
{
    return prop_get_string(gnet_property, prop, t, size);
}

void gnet_prop_set_storage(property_t p, const guint8 *v, gsize l)
{
    prop_set_storage(gnet_property, p, v, l);
}

guint8 *gnet_prop_get_storage(property_t p, guint8 *t, gsize l)
{
    return prop_get_storage(gnet_property, p, t, l);
}


/*
 * gnet_prop_get_stub:
 *
 * Returns a new stub struct for this property set. Just g_free it
 * when it is no longer needed. All fields are read only!
 */
prop_set_stub_t *gnet_prop_get_stub(void) 
{
    prop_set_stub_t *stub;

    stub          = g_new0(prop_set_stub_t, 1);
    stub->size    = GNET_PROPERTY_NUM;
    stub->offset  = GNET_PROPERTY_MIN;
    stub->get_def = gnet_prop_get_def;

    stub->prop_changed_listener.add = 
        gnet_prop_add_prop_changed_listener;
    stub->prop_changed_listener.remove = 
        gnet_prop_remove_prop_changed_listener;

    stub->boolean.get = gnet_prop_get_boolean;
    stub->boolean.set = gnet_prop_set_boolean;

    stub->guint32.get = gnet_prop_get_guint32;
    stub->guint32.set = gnet_prop_set_guint32;

    stub->string.get = gnet_prop_get_string;
    stub->string.set = gnet_prop_set_string;

    stub->storage.get = gnet_prop_get_storage;
    stub->storage.set = gnet_prop_set_storage;

    return stub;
}
