/*
 * Copyright (c) 2001-2003, Richard Eckart
 *
 * THIS FILE IS AUTOGENERATED! DO NOT EDIT!
 * This file is generated from gui_props.ag using autogen.
 * Autogen is available at http://autogen.sourceforge.net/.
 *
 *----------------------------------------------------------------------
 * This file is part of gtk-gnutella.
 *
 *  gtk-gnutella is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  gtk-gnutella is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with gtk-gnutella; if not, write to the Free Software
 *  Foundation, Inc.:
 *      59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *----------------------------------------------------------------------
 */

#include "prop.h"
#include "eval.h"
#include "gui_property.h"


/*
 * Includes specified by "uses"-statement in .ag file
 */
#include "gui.h"


#include "override.h"		/* Must be the last header included */


gboolean monitor_enabled     = FALSE;
gboolean monitor_enabled_def = FALSE;
guint32  monitor_max_items     = 25;
guint32  monitor_max_items_def = 25;
gboolean queue_regex_case     = FALSE;
gboolean queue_regex_case_def = FALSE;
gboolean search_autoselect     = TRUE;
gboolean search_autoselect_def = TRUE;
gboolean search_hide_downloaded     = FALSE;
gboolean search_hide_downloaded_def = FALSE;
guint32  nodes_col_widths[7]     = { 130, 50, 120, 20, 30, 30, 80 };
guint32  nodes_col_widths_def[7] = { 130, 50, 120, 20, 30, 30, 80 };
guint32  dl_active_col_widths[6]     = { 240, 80, 80, 80, 80, 80 };
guint32  dl_active_col_widths_def[6] = { 240, 80, 80, 80, 80, 80 };
guint32  dl_queued_col_widths[5]     = { 240, 80, 80, 80, 80 };
guint32  dl_queued_col_widths_def[5] = { 240, 80, 80, 80, 80 };
guint32  file_info_col_widths[5]     = { 240, 80, 80, 80, 80 };
guint32  file_info_col_widths_def[5] = { 240, 80, 80, 80, 80 };
guint32  search_results_col_visible[6]     = { 1,1,1,1,0,1};
guint32  search_results_col_visible_def[6] = { 1,1,1,1,0,1};
guint32  search_list_col_widths[3]     = { 80, 20, 20 };
guint32  search_list_col_widths_def[3] = { 80, 20, 20 };
guint32  search_results_col_widths[7]     = { 210, 80, 50, 70, 70, 140, 70 };
guint32  search_results_col_widths_def[7] = { 210, 80, 50, 70, 70, 140, 70 };
guint32  search_stats_col_widths[3]     = { 200, 80, 80 };
guint32  search_stats_col_widths_def[3] = { 200, 80, 80 };
guint32  ul_stats_col_widths[5]     = { 200, 80, 80, 80, 80 };
guint32  ul_stats_col_widths_def[5] = { 200, 80, 80, 80, 80 };
guint32  uploads_col_widths[6]     = { 200, 120, 36, 80, 80, 80 };
guint32  uploads_col_widths_def[6] = { 200, 120, 36, 80, 80, 80 };
guint32  filter_rules_col_widths[4]     = { 10, 240, 80, 40 };
guint32  filter_rules_col_widths_def[4] = { 10, 240, 80, 40 };
guint32  filter_filters_col_widths[3]     = { 80, 40, 20 };
guint32  filter_filters_col_widths_def[3] = { 80, 40, 20 };
guint32  gnet_stats_msg_col_widths[6]     = { 60, 20, 20, 20, 20, 20 };
guint32  gnet_stats_msg_col_widths_def[6] = { 60, 20, 20, 20, 20, 20 };
guint32  gnet_stats_fc_ttl_col_widths[10]     = { 60, 20, 20, 20, 20, 20, 20, 20, 20, 20 };
guint32  gnet_stats_fc_ttl_col_widths_def[10] = { 60, 20, 20, 20, 20, 20, 20, 20, 20, 20 };
guint32  gnet_stats_fc_hops_col_widths[10]     = { 60, 20, 20, 20, 20, 20, 20, 20, 20, 20 };
guint32  gnet_stats_fc_hops_col_widths_def[10] = { 60, 20, 20, 20, 20, 20, 20, 20, 20, 20 };
guint32  gnet_stats_fc_col_widths[10]     = { 60, 20, 20, 20, 20, 20, 20, 20, 20, 20 };
guint32  gnet_stats_fc_col_widths_def[10] = { 60, 20, 20, 20, 20, 20, 20, 20, 20, 20 };
guint32  gnet_stats_drop_reasons_col_widths[2]     = { 60, 20 };
guint32  gnet_stats_drop_reasons_col_widths_def[2] = { 60, 20 };
guint32  gnet_stats_recv_col_widths[10]     = { 60, 40, 40, 40, 40, 40, 40, 40, 40, 40 };
guint32  gnet_stats_recv_col_widths_def[10] = { 60, 40, 40, 40, 40, 40, 40, 40, 40, 40 };
guint32  window_coords[4]     = { 0, 0, 0, 0 };
guint32  window_coords_def[4] = { 0, 0, 0, 0 };
guint32  filter_dlg_coords[4]     = { 0, 0, 0, 0 };
guint32  filter_dlg_coords_def[4] = { 0, 0, 0, 0 };
guint32  downloads_divider_pos     = 220;
guint32  downloads_divider_pos_def = 220;
guint32  fileinfo_divider_pos     = 305;
guint32  fileinfo_divider_pos_def = 305;
guint32  main_divider_pos     = 140;
guint32  main_divider_pos_def = 140;
guint32  gnet_stats_divider_pos     = 300;
guint32  gnet_stats_divider_pos_def = 300;
guint32  side_divider_pos     = 100;
guint32  side_divider_pos_def = 100;
guint32  results_divider_pos     = 400;
guint32  results_divider_pos_def = 400;
guint32  search_max_results     = 5000;
guint32  search_max_results_def = 5000;
guint32  gui_debug     = 0;
guint32  gui_debug_def = 0;
guint32  filter_main_divider_pos     = 140;
guint32  filter_main_divider_pos_def = 140;
gboolean search_results_show_tabs     = FALSE;
gboolean search_results_show_tabs_def = FALSE;
gboolean toolbar_visible     = FALSE;
gboolean toolbar_visible_def = FALSE;
gboolean statusbar_visible     = TRUE;
gboolean statusbar_visible_def = TRUE;
gboolean progressbar_uploads_visible     = TRUE;
gboolean progressbar_uploads_visible_def = TRUE;
gboolean progressbar_downloads_visible     = TRUE;
gboolean progressbar_downloads_visible_def = TRUE;
gboolean progressbar_connections_visible     = TRUE;
gboolean progressbar_connections_visible_def = TRUE;
gboolean progressbar_bws_in_visible     = TRUE;
gboolean progressbar_bws_in_visible_def = TRUE;
gboolean progressbar_bws_out_visible     = TRUE;
gboolean progressbar_bws_out_visible_def = TRUE;
gboolean progressbar_bws_gin_visible     = TRUE;
gboolean progressbar_bws_gin_visible_def = TRUE;
gboolean progressbar_bws_gout_visible     = TRUE;
gboolean progressbar_bws_gout_visible_def = TRUE;
gboolean progressbar_bws_glin_visible     = TRUE;
gboolean progressbar_bws_glin_visible_def = TRUE;
gboolean progressbar_bws_glout_visible     = TRUE;
gboolean progressbar_bws_glout_visible_def = TRUE;
gboolean autohide_bws_gleaf     = TRUE;
gboolean autohide_bws_gleaf_def = TRUE;
gboolean progressbar_bws_in_avg     = TRUE;
gboolean progressbar_bws_in_avg_def = TRUE;
gboolean progressbar_bws_out_avg     = TRUE;
gboolean progressbar_bws_out_avg_def = TRUE;
gboolean progressbar_bws_gin_avg     = TRUE;
gboolean progressbar_bws_gin_avg_def = TRUE;
gboolean progressbar_bws_gout_avg     = TRUE;
gboolean progressbar_bws_gout_avg_def = TRUE;
gboolean progressbar_bws_glin_avg     = TRUE;
gboolean progressbar_bws_glin_avg_def = TRUE;
gboolean progressbar_bws_glout_avg     = TRUE;
gboolean progressbar_bws_glout_avg_def = TRUE;
gboolean search_autoselect_ident     = TRUE;
gboolean search_autoselect_ident_def = TRUE;
gboolean jump_to_downloads     = FALSE;
gboolean jump_to_downloads_def = FALSE;
gboolean show_search_results_settings     = FALSE;
gboolean show_search_results_settings_def = FALSE;
gboolean show_dl_settings     = FALSE;
gboolean show_dl_settings_def = FALSE;
gboolean search_autoselect_fuzzy     = FALSE;
gboolean search_autoselect_fuzzy_def = FALSE;
guint32  search_stats_mode     = 0;
guint32  search_stats_mode_def = 0;
prop_def_choice_t search_stats_mode_choices[] = { 
    {"disable", 0},
    {"by words", 1},
    {"by whole query", 2},
    {"by router", 3},
    {NULL, 0}
};
guint32  search_stats_update_interval     = 200;
guint32  search_stats_update_interval_def = 200;
guint32  search_stats_delcoef     = 25;
guint32  search_stats_delcoef_def = 25;
gboolean confirm_quit     = TRUE;
gboolean confirm_quit_def = TRUE;
gboolean show_tooltips     = TRUE;
gboolean show_tooltips_def = TRUE;
gboolean expert_mode     = FALSE;
gboolean expert_mode_def = FALSE;
gboolean gnet_stats_perc     = FALSE;
gboolean gnet_stats_perc_def = FALSE;
gboolean gnet_stats_bytes     = FALSE;
gboolean gnet_stats_bytes_def = FALSE;
gboolean gnet_stats_hops     = FALSE;
gboolean gnet_stats_hops_def = FALSE;
gboolean gnet_stats_with_headers     = FALSE;
gboolean gnet_stats_with_headers_def = FALSE;
gboolean gnet_stats_drop_perc     = FALSE;
gboolean gnet_stats_drop_perc_def = FALSE;
guint32  gnet_stats_general_col_widths[2]     = { 60, 20 };
guint32  gnet_stats_general_col_widths_def[2] = { 60, 20 };
gboolean clear_uploads_complete     = TRUE;
gboolean clear_uploads_complete_def = TRUE;
gboolean clear_uploads_failed     = TRUE;
gboolean clear_uploads_failed_def = TRUE;
gboolean node_show_uptime     = TRUE;
gboolean node_show_uptime_def = TRUE;
gboolean node_show_handshake_version     = FALSE;
gboolean node_show_handshake_version_def = FALSE;
gboolean node_show_detailed_info     = FALSE;
gboolean node_show_detailed_info_def = FALSE;
gboolean show_gnet_info_txc     = FALSE;
gboolean show_gnet_info_txc_def = FALSE;
gboolean show_gnet_info_rxc     = FALSE;
gboolean show_gnet_info_rxc_def = FALSE;
gboolean show_gnet_info_tx_speed     = FALSE;
gboolean show_gnet_info_tx_speed_def = FALSE;
gboolean show_gnet_info_rx_speed     = FALSE;
gboolean show_gnet_info_rx_speed_def = FALSE;
gboolean show_gnet_info_tx_queries     = FALSE;
gboolean show_gnet_info_tx_queries_def = FALSE;
gboolean show_gnet_info_rx_queries     = FALSE;
gboolean show_gnet_info_rx_queries_def = FALSE;
gboolean show_gnet_info_tx_hits     = FALSE;
gboolean show_gnet_info_tx_hits_def = FALSE;
gboolean show_gnet_info_rx_hits     = FALSE;
gboolean show_gnet_info_rx_hits_def = FALSE;
gboolean show_gnet_info_gen_queries     = FALSE;
gboolean show_gnet_info_gen_queries_def = FALSE;
gboolean show_gnet_info_sq_queries     = FALSE;
gboolean show_gnet_info_sq_queries_def = FALSE;
gboolean show_gnet_info_tx_dropped     = FALSE;
gboolean show_gnet_info_tx_dropped_def = FALSE;
gboolean show_gnet_info_rx_dropped     = FALSE;
gboolean show_gnet_info_rx_dropped_def = FALSE;
gboolean show_gnet_info_qrp_stats     = FALSE;
gboolean show_gnet_info_qrp_stats_def = FALSE;
gboolean show_gnet_info_dbw     = FALSE;
gboolean show_gnet_info_dbw_def = FALSE;
gboolean show_gnet_info_rt     = FALSE;
gboolean show_gnet_info_rt_def = FALSE;
gboolean show_gnet_info_shared_size     = FALSE;
gboolean show_gnet_info_shared_size_def = FALSE;
gboolean show_gnet_info_shared_files     = FALSE;
gboolean show_gnet_info_shared_files_def = FALSE;
guint32  search_accumulation_period     = 5;
guint32  search_accumulation_period_def = 5;
guint32  treemenu_nodes_expanded[16]     = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1 };
guint32  treemenu_nodes_expanded_def[16] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1 };
guint32  gnet_stats_pkg_col_widths[6]     = { 60, 20, 20, 20, 20, 20 };
guint32  gnet_stats_pkg_col_widths_def[6] = { 60, 20, 20, 20, 20, 20 };
guint32  gnet_stats_byte_col_widths[6]     = { 60, 20, 20, 20, 20, 20 };
guint32  gnet_stats_byte_col_widths_def[6] = { 60, 20, 20, 20, 20, 20 };
guint32  config_toolbar_style     = 4;
guint32  config_toolbar_style_def = 4;
prop_def_choice_t config_toolbar_style_choices[] = { 
    {"Icons", 1},
    {"Text", 2},
    {"Both (vertical)", 3},
    {"Both (horizontal)", 4},
    {NULL, 0}
};

static prop_set_t *gui_property = NULL;

prop_set_t *gui_prop_init(void) {
    guint32 n;

    gui_property = g_new(prop_set_t, 1);
    gui_property->name   = "gui_property";
    gui_property->desc   = "";
    gui_property->size   = GUI_PROPERTY_NUM;
    gui_property->offset = 1000;
    gui_property->mtime  = 0;
    gui_property->props  = g_new(prop_def_t, GUI_PROPERTY_NUM);
    gui_property->get_stub = gui_prop_get_stub;
    gui_property->dirty = FALSE;
    gui_property->byName = NULL;


    /*
     * PROP_MONITOR_ENABLED:
     *
     * General data:
     */
    gui_property->props[0].name = "monitor_enabled";
    gui_property->props[0].desc = _("Search monitor enabled");
    gui_property->props[0].ev_changed = event_new("monitor_enabled_changed");
    gui_property->props[0].save = TRUE;
    gui_property->props[0].vector_size = 1;

    /* Type specific data: */
    gui_property->props[0].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[0].data.boolean.def   = &monitor_enabled_def;
    gui_property->props[0].data.boolean.value = &monitor_enabled;


    /*
     * PROP_MONITOR_MAX_ITEMS:
     *
     * General data:
     */
    gui_property->props[1].name = "monitor_max_items";
    gui_property->props[1].desc = _("Maximum number of queries visible in search monitor");
    gui_property->props[1].ev_changed = event_new("monitor_max_items_changed");
    gui_property->props[1].save = TRUE;
    gui_property->props[1].vector_size = 1;

    /* Type specific data: */
    gui_property->props[1].type               = PROP_TYPE_GUINT32;
    gui_property->props[1].data.guint32.def   = &monitor_max_items_def;
    gui_property->props[1].data.guint32.value = &monitor_max_items;
    gui_property->props[1].data.guint32.choices = NULL;
    gui_property->props[1].data.guint32.max   = 100;
    gui_property->props[1].data.guint32.min   = 0;


    /*
     * PROP_QUEUE_REGEX_CASE:
     *
     * General data:
     */
    gui_property->props[2].name = "queue_regex_case";
    gui_property->props[2].desc = _("Match queue selection by regexp case sensitive");
    gui_property->props[2].ev_changed = event_new("queue_regex_case_changed");
    gui_property->props[2].save = TRUE;
    gui_property->props[2].vector_size = 1;

    /* Type specific data: */
    gui_property->props[2].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[2].data.boolean.def   = &queue_regex_case_def;
    gui_property->props[2].data.boolean.value = &queue_regex_case;


    /*
     * PROP_SEARCH_AUTOSELECT:
     *
     * General data:
     */
    gui_property->props[3].name = "search_autoselect";
    gui_property->props[3].desc = _("Autoselect similar files in searches");
    gui_property->props[3].ev_changed = event_new("search_autoselect_changed");
    gui_property->props[3].save = TRUE;
    gui_property->props[3].vector_size = 1;

    /* Type specific data: */
    gui_property->props[3].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[3].data.boolean.def   = &search_autoselect_def;
    gui_property->props[3].data.boolean.value = &search_autoselect;


    /*
     * PROP_SEARCH_HIDE_DOWNLOADED:
     *
     * General data:
     */
    gui_property->props[4].name = "search_hide_downloaded";
    gui_property->props[4].desc = _("Whether to hide hits that have been considered for auto-downloading based on the SHA1 or your filters.");
    gui_property->props[4].ev_changed = event_new("search_hide_downloaded_changed");
    gui_property->props[4].save = TRUE;
    gui_property->props[4].vector_size = 1;

    /* Type specific data: */
    gui_property->props[4].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[4].data.boolean.def   = &search_hide_downloaded_def;
    gui_property->props[4].data.boolean.value = &search_hide_downloaded;


    /*
     * PROP_NODES_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[5].name = "widths_nodes";
    gui_property->props[5].desc = _("Widths of the columns in the nodes table");
    gui_property->props[5].ev_changed = event_new("nodes_col_widths_changed");
    gui_property->props[5].save = TRUE;
    gui_property->props[5].vector_size = 7;

    /* Type specific data: */
    gui_property->props[5].type               = PROP_TYPE_GUINT32;
    gui_property->props[5].data.guint32.def   = nodes_col_widths_def;
    gui_property->props[5].data.guint32.value = nodes_col_widths;
    gui_property->props[5].data.guint32.choices = NULL;
    gui_property->props[5].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[5].data.guint32.min   = 0x00000000;


    /*
     * PROP_DL_ACTIVE_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[6].name = "widths_dl_active";
    gui_property->props[6].desc = _("Widths of the columns in the active downloads table");
    gui_property->props[6].ev_changed = event_new("dl_active_col_widths_changed");
    gui_property->props[6].save = TRUE;
    gui_property->props[6].vector_size = 6;

    /* Type specific data: */
    gui_property->props[6].type               = PROP_TYPE_GUINT32;
    gui_property->props[6].data.guint32.def   = dl_active_col_widths_def;
    gui_property->props[6].data.guint32.value = dl_active_col_widths;
    gui_property->props[6].data.guint32.choices = NULL;
    gui_property->props[6].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[6].data.guint32.min   = 0x00000000;


    /*
     * PROP_DL_QUEUED_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[7].name = "widths_dl_queued";
    gui_property->props[7].desc = _("Widths of the columns in the queued downloads table");
    gui_property->props[7].ev_changed = event_new("dl_queued_col_widths_changed");
    gui_property->props[7].save = TRUE;
    gui_property->props[7].vector_size = 5;

    /* Type specific data: */
    gui_property->props[7].type               = PROP_TYPE_GUINT32;
    gui_property->props[7].data.guint32.def   = dl_queued_col_widths_def;
    gui_property->props[7].data.guint32.value = dl_queued_col_widths;
    gui_property->props[7].data.guint32.choices = NULL;
    gui_property->props[7].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[7].data.guint32.min   = 0x00000000;


    /*
     * PROP_FILE_INFO_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[8].name = "widths_file_info";
    gui_property->props[8].desc = _("Widths of the columns in the file info table");
    gui_property->props[8].ev_changed = event_new("file_info_col_widths_changed");
    gui_property->props[8].save = TRUE;
    gui_property->props[8].vector_size = 5;

    /* Type specific data: */
    gui_property->props[8].type               = PROP_TYPE_GUINT32;
    gui_property->props[8].data.guint32.def   = file_info_col_widths_def;
    gui_property->props[8].data.guint32.value = file_info_col_widths;
    gui_property->props[8].data.guint32.choices = NULL;
    gui_property->props[8].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[8].data.guint32.min   = 0x00000000;


    /*
     * PROP_SEARCH_RESULTS_COL_VISIBLE:
     *
     * General data:
     */
    gui_property->props[9].name = "search_results_col_visible";
    gui_property->props[9].desc = _("Which columns are visible in the search results tables");
    gui_property->props[9].ev_changed = event_new("search_results_col_visible_changed");
    gui_property->props[9].save = TRUE;
    gui_property->props[9].vector_size = 6;

    /* Type specific data: */
    gui_property->props[9].type               = PROP_TYPE_GUINT32;
    gui_property->props[9].data.guint32.def   = search_results_col_visible_def;
    gui_property->props[9].data.guint32.value = search_results_col_visible;
    gui_property->props[9].data.guint32.choices = NULL;
    gui_property->props[9].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[9].data.guint32.min   = 0x00000000;


    /*
     * PROP_SEARCH_LIST_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[10].name = "widths_search_list";
    gui_property->props[10].desc = _("Widths of the columns in the search list on the sidebar");
    gui_property->props[10].ev_changed = event_new("search_list_col_widths_changed");
    gui_property->props[10].save = TRUE;
    gui_property->props[10].vector_size = 3;

    /* Type specific data: */
    gui_property->props[10].type               = PROP_TYPE_GUINT32;
    gui_property->props[10].data.guint32.def   = search_list_col_widths_def;
    gui_property->props[10].data.guint32.value = search_list_col_widths;
    gui_property->props[10].data.guint32.choices = NULL;
    gui_property->props[10].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[10].data.guint32.min   = 0x00000000;


    /*
     * PROP_SEARCH_RESULTS_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[11].name = "widths_search_results";
    gui_property->props[11].desc = _("Widths of the columns in the search results tables");
    gui_property->props[11].ev_changed = event_new("search_results_col_widths_changed");
    gui_property->props[11].save = TRUE;
    gui_property->props[11].vector_size = 7;

    /* Type specific data: */
    gui_property->props[11].type               = PROP_TYPE_GUINT32;
    gui_property->props[11].data.guint32.def   = search_results_col_widths_def;
    gui_property->props[11].data.guint32.value = search_results_col_widths;
    gui_property->props[11].data.guint32.choices = NULL;
    gui_property->props[11].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[11].data.guint32.min   = 0x00000000;


    /*
     * PROP_SEARCH_STATS_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[12].name = "widths_search_stats";
    gui_property->props[12].desc = _("Widths of the columns in the search stats table");
    gui_property->props[12].ev_changed = event_new("search_stats_col_widths_changed");
    gui_property->props[12].save = TRUE;
    gui_property->props[12].vector_size = 3;

    /* Type specific data: */
    gui_property->props[12].type               = PROP_TYPE_GUINT32;
    gui_property->props[12].data.guint32.def   = search_stats_col_widths_def;
    gui_property->props[12].data.guint32.value = search_stats_col_widths;
    gui_property->props[12].data.guint32.choices = NULL;
    gui_property->props[12].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[12].data.guint32.min   = 0x00000000;


    /*
     * PROP_UL_STATS_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[13].name = "widths_ul_stats";
    gui_property->props[13].desc = _("Widths of the columns in the upload stats table");
    gui_property->props[13].ev_changed = event_new("ul_stats_col_widths_changed");
    gui_property->props[13].save = TRUE;
    gui_property->props[13].vector_size = 5;

    /* Type specific data: */
    gui_property->props[13].type               = PROP_TYPE_GUINT32;
    gui_property->props[13].data.guint32.def   = ul_stats_col_widths_def;
    gui_property->props[13].data.guint32.value = ul_stats_col_widths;
    gui_property->props[13].data.guint32.choices = NULL;
    gui_property->props[13].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[13].data.guint32.min   = 0x00000000;


    /*
     * PROP_UPLOADS_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[14].name = "widths_uploads";
    gui_property->props[14].desc = _("Widths of the columns in the uploads table");
    gui_property->props[14].ev_changed = event_new("uploads_col_widths_changed");
    gui_property->props[14].save = TRUE;
    gui_property->props[14].vector_size = 6;

    /* Type specific data: */
    gui_property->props[14].type               = PROP_TYPE_GUINT32;
    gui_property->props[14].data.guint32.def   = uploads_col_widths_def;
    gui_property->props[14].data.guint32.value = uploads_col_widths;
    gui_property->props[14].data.guint32.choices = NULL;
    gui_property->props[14].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[14].data.guint32.min   = 0x00000000;


    /*
     * PROP_FILTER_RULES_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[15].name = "widths_filter_table";
    gui_property->props[15].desc = _("Widths of the columns in the rules table in the filter dialog");
    gui_property->props[15].ev_changed = event_new("filter_rules_col_widths_changed");
    gui_property->props[15].save = TRUE;
    gui_property->props[15].vector_size = 4;

    /* Type specific data: */
    gui_property->props[15].type               = PROP_TYPE_GUINT32;
    gui_property->props[15].data.guint32.def   = filter_rules_col_widths_def;
    gui_property->props[15].data.guint32.value = filter_rules_col_widths;
    gui_property->props[15].data.guint32.choices = NULL;
    gui_property->props[15].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[15].data.guint32.min   = 0x00000000;


    /*
     * PROP_FILTER_FILTERS_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[16].name = "widths_filter_filters";
    gui_property->props[16].desc = _("Widths of the columns in the filter table in the filter dialog");
    gui_property->props[16].ev_changed = event_new("filter_filters_col_widths_changed");
    gui_property->props[16].save = TRUE;
    gui_property->props[16].vector_size = 3;

    /* Type specific data: */
    gui_property->props[16].type               = PROP_TYPE_GUINT32;
    gui_property->props[16].data.guint32.def   = filter_filters_col_widths_def;
    gui_property->props[16].data.guint32.value = filter_filters_col_widths;
    gui_property->props[16].data.guint32.choices = NULL;
    gui_property->props[16].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[16].data.guint32.min   = 0x00000000;


    /*
     * PROP_GNET_STATS_MSG_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[17].name = "widths_gnet_stats_msg";
    gui_property->props[17].desc = _("Widths of the columns in the gnet packet stats table");
    gui_property->props[17].ev_changed = event_new("gnet_stats_msg_col_widths_changed");
    gui_property->props[17].save = TRUE;
    gui_property->props[17].vector_size = 6;

    /* Type specific data: */
    gui_property->props[17].type               = PROP_TYPE_GUINT32;
    gui_property->props[17].data.guint32.def   = gnet_stats_msg_col_widths_def;
    gui_property->props[17].data.guint32.value = gnet_stats_msg_col_widths;
    gui_property->props[17].data.guint32.choices = NULL;
    gui_property->props[17].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[17].data.guint32.min   = 0x00000000;


    /*
     * PROP_GNET_STATS_FC_TTL_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[18].name = "widths_gnet_stats_fc_ttl";
    gui_property->props[18].desc = _("Widths of the columns in the gnet fc ttl stats table");
    gui_property->props[18].ev_changed = event_new("gnet_stats_fc_ttl_col_widths_changed");
    gui_property->props[18].save = TRUE;
    gui_property->props[18].vector_size = 10;

    /* Type specific data: */
    gui_property->props[18].type               = PROP_TYPE_GUINT32;
    gui_property->props[18].data.guint32.def   = gnet_stats_fc_ttl_col_widths_def;
    gui_property->props[18].data.guint32.value = gnet_stats_fc_ttl_col_widths;
    gui_property->props[18].data.guint32.choices = NULL;
    gui_property->props[18].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[18].data.guint32.min   = 0x00000000;


    /*
     * PROP_GNET_STATS_FC_HOPS_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[19].name = "widths_gnet_stats_fc_hops";
    gui_property->props[19].desc = _("Widths of the columns in the gnet fc hops stats table");
    gui_property->props[19].ev_changed = event_new("gnet_stats_fc_hops_col_widths_changed");
    gui_property->props[19].save = TRUE;
    gui_property->props[19].vector_size = 10;

    /* Type specific data: */
    gui_property->props[19].type               = PROP_TYPE_GUINT32;
    gui_property->props[19].data.guint32.def   = gnet_stats_fc_hops_col_widths_def;
    gui_property->props[19].data.guint32.value = gnet_stats_fc_hops_col_widths;
    gui_property->props[19].data.guint32.choices = NULL;
    gui_property->props[19].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[19].data.guint32.min   = 0x00000000;


    /*
     * PROP_GNET_STATS_FC_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[20].name = "widths_gnet_stats_fc";
    gui_property->props[20].desc = _("Widths of the columns in the gnet fc hops stats table");
    gui_property->props[20].ev_changed = event_new("gnet_stats_fc_col_widths_changed");
    gui_property->props[20].save = TRUE;
    gui_property->props[20].vector_size = 10;

    /* Type specific data: */
    gui_property->props[20].type               = PROP_TYPE_GUINT32;
    gui_property->props[20].data.guint32.def   = gnet_stats_fc_col_widths_def;
    gui_property->props[20].data.guint32.value = gnet_stats_fc_col_widths;
    gui_property->props[20].data.guint32.choices = NULL;
    gui_property->props[20].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[20].data.guint32.min   = 0x00000000;


    /*
     * PROP_GNET_STATS_DROP_REASONS_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[21].name = "widths_gnet_stats_drop_reasons";
    gui_property->props[21].desc = _("Widths of the columns in the gnet stats drop reasons table");
    gui_property->props[21].ev_changed = event_new("gnet_stats_drop_reasons_col_widths_changed");
    gui_property->props[21].save = TRUE;
    gui_property->props[21].vector_size = 2;

    /* Type specific data: */
    gui_property->props[21].type               = PROP_TYPE_GUINT32;
    gui_property->props[21].data.guint32.def   = gnet_stats_drop_reasons_col_widths_def;
    gui_property->props[21].data.guint32.value = gnet_stats_drop_reasons_col_widths;
    gui_property->props[21].data.guint32.choices = NULL;
    gui_property->props[21].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[21].data.guint32.min   = 0x00000000;


    /*
     * PROP_GNET_STATS_RECV_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[22].name = "widths_gnet_stats_recv";
    gui_property->props[22].desc = _("Widths of the columns in the gnet stats drop reasons table");
    gui_property->props[22].ev_changed = event_new("gnet_stats_recv_col_widths_changed");
    gui_property->props[22].save = TRUE;
    gui_property->props[22].vector_size = 10;

    /* Type specific data: */
    gui_property->props[22].type               = PROP_TYPE_GUINT32;
    gui_property->props[22].data.guint32.def   = gnet_stats_recv_col_widths_def;
    gui_property->props[22].data.guint32.value = gnet_stats_recv_col_widths;
    gui_property->props[22].data.guint32.choices = NULL;
    gui_property->props[22].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[22].data.guint32.min   = 0x00000000;


    /*
     * PROP_WINDOW_COORDS:
     *
     * General data:
     */
    gui_property->props[23].name = "window_coords";
    gui_property->props[23].desc = _("Position and size of the main window");
    gui_property->props[23].ev_changed = event_new("window_coords_changed");
    gui_property->props[23].save = TRUE;
    gui_property->props[23].vector_size = 4;

    /* Type specific data: */
    gui_property->props[23].type               = PROP_TYPE_GUINT32;
    gui_property->props[23].data.guint32.def   = window_coords_def;
    gui_property->props[23].data.guint32.value = window_coords;
    gui_property->props[23].data.guint32.choices = NULL;
    gui_property->props[23].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[23].data.guint32.min   = 0x00000000;


    /*
     * PROP_FILTER_DLG_COORDS:
     *
     * General data:
     */
    gui_property->props[24].name = "filter_dlg_coords";
    gui_property->props[24].desc = _("Position and size of the filter dialog");
    gui_property->props[24].ev_changed = event_new("filter_dlg_coords_changed");
    gui_property->props[24].save = TRUE;
    gui_property->props[24].vector_size = 4;

    /* Type specific data: */
    gui_property->props[24].type               = PROP_TYPE_GUINT32;
    gui_property->props[24].data.guint32.def   = filter_dlg_coords_def;
    gui_property->props[24].data.guint32.value = filter_dlg_coords;
    gui_property->props[24].data.guint32.choices = NULL;
    gui_property->props[24].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[24].data.guint32.min   = 0x00000000;


    /*
     * PROP_DOWNLOADS_DIVIDER_POS:
     *
     * General data:
     */
    gui_property->props[25].name = "downloads_divider_pos";
    gui_property->props[25].desc = _("Position of the divider in the downloads panel");
    gui_property->props[25].ev_changed = event_new("downloads_divider_pos_changed");
    gui_property->props[25].save = TRUE;
    gui_property->props[25].vector_size = 1;

    /* Type specific data: */
    gui_property->props[25].type               = PROP_TYPE_GUINT32;
    gui_property->props[25].data.guint32.def   = &downloads_divider_pos_def;
    gui_property->props[25].data.guint32.value = &downloads_divider_pos;
    gui_property->props[25].data.guint32.choices = NULL;
    gui_property->props[25].data.guint32.max   = 0xFFFF;
    gui_property->props[25].data.guint32.min   = 0x0000;


    /*
     * PROP_FILEINFO_DIVIDER_POS:
     *
     * General data:
     */
    gui_property->props[26].name = "fileinfo_divider_pos";
    gui_property->props[26].desc = _("Position of the divider in the fileinfo panel");
    gui_property->props[26].ev_changed = event_new("fileinfo_divider_pos_changed");
    gui_property->props[26].save = TRUE;
    gui_property->props[26].vector_size = 1;

    /* Type specific data: */
    gui_property->props[26].type               = PROP_TYPE_GUINT32;
    gui_property->props[26].data.guint32.def   = &fileinfo_divider_pos_def;
    gui_property->props[26].data.guint32.value = &fileinfo_divider_pos;
    gui_property->props[26].data.guint32.choices = NULL;
    gui_property->props[26].data.guint32.max   = 0xFFFF;
    gui_property->props[26].data.guint32.min   = 0x0000;


    /*
     * PROP_MAIN_DIVIDER_POS:
     *
     * General data:
     */
    gui_property->props[27].name = "main_divider_pos";
    gui_property->props[27].desc = _("Size of the sidebar");
    gui_property->props[27].ev_changed = event_new("main_divider_pos_changed");
    gui_property->props[27].save = TRUE;
    gui_property->props[27].vector_size = 1;

    /* Type specific data: */
    gui_property->props[27].type               = PROP_TYPE_GUINT32;
    gui_property->props[27].data.guint32.def   = &main_divider_pos_def;
    gui_property->props[27].data.guint32.value = &main_divider_pos;
    gui_property->props[27].data.guint32.choices = NULL;
    gui_property->props[27].data.guint32.max   = 0xFFFF;
    gui_property->props[27].data.guint32.min   = 0x0000;


    /*
     * PROP_GNET_STATS_DIVIDER_POS:
     *
     * General data:
     */
    gui_property->props[28].name = "gnet_stats_divider_pos";
    gui_property->props[28].desc = _("Position of the divider in the gnet stats pane");
    gui_property->props[28].ev_changed = event_new("gnet_stats_divider_pos_changed");
    gui_property->props[28].save = TRUE;
    gui_property->props[28].vector_size = 1;

    /* Type specific data: */
    gui_property->props[28].type               = PROP_TYPE_GUINT32;
    gui_property->props[28].data.guint32.def   = &gnet_stats_divider_pos_def;
    gui_property->props[28].data.guint32.value = &gnet_stats_divider_pos;
    gui_property->props[28].data.guint32.choices = NULL;
    gui_property->props[28].data.guint32.max   = 0xFFFF;
    gui_property->props[28].data.guint32.min   = 0x0000;


    /*
     * PROP_SIDE_DIVIDER_POS:
     *
     * General data:
     */
    gui_property->props[29].name = "side_divider_pos";
    gui_property->props[29].desc = _("Size of the menu in the sidebar");
    gui_property->props[29].ev_changed = event_new("side_divider_pos_changed");
    gui_property->props[29].save = TRUE;
    gui_property->props[29].vector_size = 1;

    /* Type specific data: */
    gui_property->props[29].type               = PROP_TYPE_GUINT32;
    gui_property->props[29].data.guint32.def   = &side_divider_pos_def;
    gui_property->props[29].data.guint32.value = &side_divider_pos;
    gui_property->props[29].data.guint32.choices = NULL;
    gui_property->props[29].data.guint32.max   = 0xFFFF;
    gui_property->props[29].data.guint32.min   = 0x0000;


    /*
     * PROP_RESULTS_DIVIDER_POS:
     *
     * General data:
     */
    gui_property->props[30].name = "results_divider_pos";
    gui_property->props[30].desc = _("Position of the divider in the search results pane");
    gui_property->props[30].ev_changed = event_new("results_divider_pos_changed");
    gui_property->props[30].save = TRUE;
    gui_property->props[30].vector_size = 1;

    /* Type specific data: */
    gui_property->props[30].type               = PROP_TYPE_GUINT32;
    gui_property->props[30].data.guint32.def   = &results_divider_pos_def;
    gui_property->props[30].data.guint32.value = &results_divider_pos;
    gui_property->props[30].data.guint32.choices = NULL;
    gui_property->props[30].data.guint32.max   = 0xFFFF;
    gui_property->props[30].data.guint32.min   = 0x0000;


    /*
     * PROP_SEARCH_MAX_RESULTS:
     *
     * General data:
     */
    gui_property->props[31].name = "search_max_results";
    gui_property->props[31].desc = _("Maximum number of results to show in any search");
    gui_property->props[31].ev_changed = event_new("search_max_results_changed");
    gui_property->props[31].save = TRUE;
    gui_property->props[31].vector_size = 1;

    /* Type specific data: */
    gui_property->props[31].type               = PROP_TYPE_GUINT32;
    gui_property->props[31].data.guint32.def   = &search_max_results_def;
    gui_property->props[31].data.guint32.value = &search_max_results;
    gui_property->props[31].data.guint32.choices = NULL;
    gui_property->props[31].data.guint32.max   = 100000;
    gui_property->props[31].data.guint32.min   = 10;


    /*
     * PROP_GUI_DEBUG:
     *
     * General data:
     */
    gui_property->props[32].name = "gui_debug";
    gui_property->props[32].desc = _("Debug level for the gui");
    gui_property->props[32].ev_changed = event_new("gui_debug_changed");
    gui_property->props[32].save = TRUE;
    gui_property->props[32].vector_size = 1;

    /* Type specific data: */
    gui_property->props[32].type               = PROP_TYPE_GUINT32;
    gui_property->props[32].data.guint32.def   = &gui_debug_def;
    gui_property->props[32].data.guint32.value = &gui_debug;
    gui_property->props[32].data.guint32.choices = NULL;
    gui_property->props[32].data.guint32.max   = 20;
    gui_property->props[32].data.guint32.min   = 0;


    /*
     * PROP_FILTER_MAIN_DIVIDER_POS:
     *
     * General data:
     */
    gui_property->props[33].name = "filter_main_divider_pos";
    gui_property->props[33].desc = _("Size of the filter tree in the filter dialog");
    gui_property->props[33].ev_changed = event_new("filter_main_divider_pos_changed");
    gui_property->props[33].save = TRUE;
    gui_property->props[33].vector_size = 1;

    /* Type specific data: */
    gui_property->props[33].type               = PROP_TYPE_GUINT32;
    gui_property->props[33].data.guint32.def   = &filter_main_divider_pos_def;
    gui_property->props[33].data.guint32.value = &filter_main_divider_pos;
    gui_property->props[33].data.guint32.choices = NULL;
    gui_property->props[33].data.guint32.max   = 0xFFFF;
    gui_property->props[33].data.guint32.min   = 0x0000;


    /*
     * PROP_SEARCH_RESULTS_SHOW_TABS:
     *
     * General data:
     */
    gui_property->props[34].name = "search_results_show_tabs";
    gui_property->props[34].desc = _("Show tabs or search list");
    gui_property->props[34].ev_changed = event_new("search_results_show_tabs_changed");
    gui_property->props[34].save = TRUE;
    gui_property->props[34].vector_size = 1;

    /* Type specific data: */
    gui_property->props[34].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[34].data.boolean.def   = &search_results_show_tabs_def;
    gui_property->props[34].data.boolean.value = &search_results_show_tabs;


    /*
     * PROP_TOOLBAR_VISIBLE:
     *
     * General data:
     */
    gui_property->props[35].name = "toolbar_visible";
    gui_property->props[35].desc = _("Display toolbar");
    gui_property->props[35].ev_changed = event_new("toolbar_visible_changed");
    gui_property->props[35].save = TRUE;
    gui_property->props[35].vector_size = 1;

    /* Type specific data: */
    gui_property->props[35].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[35].data.boolean.def   = &toolbar_visible_def;
    gui_property->props[35].data.boolean.value = &toolbar_visible;


    /*
     * PROP_STATUSBAR_VISIBLE:
     *
     * General data:
     */
    gui_property->props[36].name = "statusbar_visible";
    gui_property->props[36].desc = _("Display statusbar");
    gui_property->props[36].ev_changed = event_new("statusbar_visible_changed");
    gui_property->props[36].save = TRUE;
    gui_property->props[36].vector_size = 1;

    /* Type specific data: */
    gui_property->props[36].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[36].data.boolean.def   = &statusbar_visible_def;
    gui_property->props[36].data.boolean.value = &statusbar_visible;


    /*
     * PROP_PROGRESSBAR_UPLOADS_VISIBLE:
     *
     * General data:
     */
    gui_property->props[37].name = "progressbar_uploads_visible";
    gui_property->props[37].desc = _("Display upload statistics in sidebar");
    gui_property->props[37].ev_changed = event_new("progressbar_uploads_visible_changed");
    gui_property->props[37].save = TRUE;
    gui_property->props[37].vector_size = 1;

    /* Type specific data: */
    gui_property->props[37].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[37].data.boolean.def   = &progressbar_uploads_visible_def;
    gui_property->props[37].data.boolean.value = &progressbar_uploads_visible;


    /*
     * PROP_PROGRESSBAR_DOWNLOADS_VISIBLE:
     *
     * General data:
     */
    gui_property->props[38].name = "progressbar_downloads_visible";
    gui_property->props[38].desc = _("Display download statistics in sidebar");
    gui_property->props[38].ev_changed = event_new("progressbar_downloads_visible_changed");
    gui_property->props[38].save = TRUE;
    gui_property->props[38].vector_size = 1;

    /* Type specific data: */
    gui_property->props[38].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[38].data.boolean.def   = &progressbar_downloads_visible_def;
    gui_property->props[38].data.boolean.value = &progressbar_downloads_visible;


    /*
     * PROP_PROGRESSBAR_CONNECTIONS_VISIBLE:
     *
     * General data:
     */
    gui_property->props[39].name = "progressbar_connections_visible";
    gui_property->props[39].desc = _("Display connection statistics in sidebar");
    gui_property->props[39].ev_changed = event_new("progressbar_connections_visible_changed");
    gui_property->props[39].save = TRUE;
    gui_property->props[39].vector_size = 1;

    /* Type specific data: */
    gui_property->props[39].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[39].data.boolean.def   = &progressbar_connections_visible_def;
    gui_property->props[39].data.boolean.value = &progressbar_connections_visible;


    /*
     * PROP_PROGRESSBAR_BWS_IN_VISIBLE:
     *
     * General data:
     */
    gui_property->props[40].name = "progressbar_bws_in_visible";
    gui_property->props[40].desc = _("Display incoming HTTP traffic bandwidth usage");
    gui_property->props[40].ev_changed = event_new("progressbar_bws_in_visible_changed");
    gui_property->props[40].save = TRUE;
    gui_property->props[40].vector_size = 1;

    /* Type specific data: */
    gui_property->props[40].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[40].data.boolean.def   = &progressbar_bws_in_visible_def;
    gui_property->props[40].data.boolean.value = &progressbar_bws_in_visible;


    /*
     * PROP_PROGRESSBAR_BWS_OUT_VISIBLE:
     *
     * General data:
     */
    gui_property->props[41].name = "progressbar_bws_out_visible";
    gui_property->props[41].desc = _("Display outgoing HTTP traffic bandwidth usage");
    gui_property->props[41].ev_changed = event_new("progressbar_bws_out_visible_changed");
    gui_property->props[41].save = TRUE;
    gui_property->props[41].vector_size = 1;

    /* Type specific data: */
    gui_property->props[41].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[41].data.boolean.def   = &progressbar_bws_out_visible_def;
    gui_property->props[41].data.boolean.value = &progressbar_bws_out_visible;


    /*
     * PROP_PROGRESSBAR_BWS_GIN_VISIBLE:
     *
     * General data:
     */
    gui_property->props[42].name = "progressbar_bws_gin_visible";
    gui_property->props[42].desc = _("Display incoming gNet traffic bandwidth usage");
    gui_property->props[42].ev_changed = event_new("progressbar_bws_gin_visible_changed");
    gui_property->props[42].save = TRUE;
    gui_property->props[42].vector_size = 1;

    /* Type specific data: */
    gui_property->props[42].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[42].data.boolean.def   = &progressbar_bws_gin_visible_def;
    gui_property->props[42].data.boolean.value = &progressbar_bws_gin_visible;


    /*
     * PROP_PROGRESSBAR_BWS_GOUT_VISIBLE:
     *
     * General data:
     */
    gui_property->props[43].name = "progressbar_bws_gout_visible";
    gui_property->props[43].desc = _("Display outgoing gNet traffic bandwidth usage");
    gui_property->props[43].ev_changed = event_new("progressbar_bws_gout_visible_changed");
    gui_property->props[43].save = TRUE;
    gui_property->props[43].vector_size = 1;

    /* Type specific data: */
    gui_property->props[43].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[43].data.boolean.def   = &progressbar_bws_gout_visible_def;
    gui_property->props[43].data.boolean.value = &progressbar_bws_gout_visible;


    /*
     * PROP_PROGRESSBAR_BWS_GLIN_VISIBLE:
     *
     * General data:
     */
    gui_property->props[44].name = "progressbar_bws_glin_visible";
    gui_property->props[44].desc = _("Display incoming gNet leaf traffic bandwidth usage");
    gui_property->props[44].ev_changed = event_new("progressbar_bws_glin_visible_changed");
    gui_property->props[44].save = TRUE;
    gui_property->props[44].vector_size = 1;

    /* Type specific data: */
    gui_property->props[44].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[44].data.boolean.def   = &progressbar_bws_glin_visible_def;
    gui_property->props[44].data.boolean.value = &progressbar_bws_glin_visible;


    /*
     * PROP_PROGRESSBAR_BWS_GLOUT_VISIBLE:
     *
     * General data:
     */
    gui_property->props[45].name = "progressbar_bws_glout_visible";
    gui_property->props[45].desc = _("Display outgoing gNet leaf traffic bandwidth usage");
    gui_property->props[45].ev_changed = event_new("progressbar_bws_glout_visible_changed");
    gui_property->props[45].save = TRUE;
    gui_property->props[45].vector_size = 1;

    /* Type specific data: */
    gui_property->props[45].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[45].data.boolean.def   = &progressbar_bws_glout_visible_def;
    gui_property->props[45].data.boolean.value = &progressbar_bws_glout_visible;


    /*
     * PROP_AUTOHIDE_BWS_GLEAF:
     *
     * General data:
     */
    gui_property->props[46].name = "autohide_bws_gleaf";
    gui_property->props[46].desc = _("Automatically hide leaf bandwidth display when not in ultrapeer mode");
    gui_property->props[46].ev_changed = event_new("autohide_bws_gleaf_changed");
    gui_property->props[46].save = TRUE;
    gui_property->props[46].vector_size = 1;

    /* Type specific data: */
    gui_property->props[46].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[46].data.boolean.def   = &autohide_bws_gleaf_def;
    gui_property->props[46].data.boolean.value = &autohide_bws_gleaf;


    /*
     * PROP_PROGRESSBAR_BWS_IN_AVG:
     *
     * General data:
     */
    gui_property->props[47].name = "progressbar_bws_in_avg";
    gui_property->props[47].desc = _("Display incoming HTTP traffic bandwidth average");
    gui_property->props[47].ev_changed = event_new("progressbar_bws_in_avg_changed");
    gui_property->props[47].save = TRUE;
    gui_property->props[47].vector_size = 1;

    /* Type specific data: */
    gui_property->props[47].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[47].data.boolean.def   = &progressbar_bws_in_avg_def;
    gui_property->props[47].data.boolean.value = &progressbar_bws_in_avg;


    /*
     * PROP_PROGRESSBAR_BWS_OUT_AVG:
     *
     * General data:
     */
    gui_property->props[48].name = "progressbar_bws_out_avg";
    gui_property->props[48].desc = _("Display outgoing HTTP traffic bandwidth average");
    gui_property->props[48].ev_changed = event_new("progressbar_bws_out_avg_changed");
    gui_property->props[48].save = TRUE;
    gui_property->props[48].vector_size = 1;

    /* Type specific data: */
    gui_property->props[48].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[48].data.boolean.def   = &progressbar_bws_out_avg_def;
    gui_property->props[48].data.boolean.value = &progressbar_bws_out_avg;


    /*
     * PROP_PROGRESSBAR_BWS_GIN_AVG:
     *
     * General data:
     */
    gui_property->props[49].name = "progressbar_bws_gin_avg";
    gui_property->props[49].desc = _("Display incoming gNet traffic bandwidth average");
    gui_property->props[49].ev_changed = event_new("progressbar_bws_gin_avg_changed");
    gui_property->props[49].save = TRUE;
    gui_property->props[49].vector_size = 1;

    /* Type specific data: */
    gui_property->props[49].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[49].data.boolean.def   = &progressbar_bws_gin_avg_def;
    gui_property->props[49].data.boolean.value = &progressbar_bws_gin_avg;


    /*
     * PROP_PROGRESSBAR_BWS_GOUT_AVG:
     *
     * General data:
     */
    gui_property->props[50].name = "progressbar_bws_gout_avg";
    gui_property->props[50].desc = _("Display outgoing gNet traffic bandwidth average");
    gui_property->props[50].ev_changed = event_new("progressbar_bws_gout_avg_changed");
    gui_property->props[50].save = TRUE;
    gui_property->props[50].vector_size = 1;

    /* Type specific data: */
    gui_property->props[50].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[50].data.boolean.def   = &progressbar_bws_gout_avg_def;
    gui_property->props[50].data.boolean.value = &progressbar_bws_gout_avg;


    /*
     * PROP_PROGRESSBAR_BWS_GLIN_AVG:
     *
     * General data:
     */
    gui_property->props[51].name = "progressbar_bws_glin_avg";
    gui_property->props[51].desc = _("Display incoming gNet leaf traffic bandwidth average");
    gui_property->props[51].ev_changed = event_new("progressbar_bws_glin_avg_changed");
    gui_property->props[51].save = TRUE;
    gui_property->props[51].vector_size = 1;

    /* Type specific data: */
    gui_property->props[51].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[51].data.boolean.def   = &progressbar_bws_glin_avg_def;
    gui_property->props[51].data.boolean.value = &progressbar_bws_glin_avg;


    /*
     * PROP_PROGRESSBAR_BWS_GLOUT_AVG:
     *
     * General data:
     */
    gui_property->props[52].name = "progressbar_bws_glout_avg";
    gui_property->props[52].desc = _("Display outgoing gNet leaf traffic bandwidth average");
    gui_property->props[52].ev_changed = event_new("progressbar_bws_glout_avg_changed");
    gui_property->props[52].save = TRUE;
    gui_property->props[52].vector_size = 1;

    /* Type specific data: */
    gui_property->props[52].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[52].data.boolean.def   = &progressbar_bws_glout_avg_def;
    gui_property->props[52].data.boolean.value = &progressbar_bws_glout_avg;


    /*
     * PROP_SEARCH_AUTOSELECT_IDENT:
     *
     * General data:
     */
    gui_property->props[53].name = "search_autoselect_ident";
    gui_property->props[53].desc = _("When enabled autoselection only takes place if filesize matches exactly, otherwise it must be equal or greater");
    gui_property->props[53].ev_changed = event_new("search_autoselect_ident_changed");
    gui_property->props[53].save = TRUE;
    gui_property->props[53].vector_size = 1;

    /* Type specific data: */
    gui_property->props[53].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[53].data.boolean.def   = &search_autoselect_ident_def;
    gui_property->props[53].data.boolean.value = &search_autoselect_ident;


    /*
     * PROP_JUMP_TO_DOWNLOADS:
     *
     * General data:
     */
    gui_property->props[54].name = "jump_to_downloads";
    gui_property->props[54].desc = _("Jump to downloads screen when downloading a file");
    gui_property->props[54].ev_changed = event_new("jump_to_downloads_changed");
    gui_property->props[54].save = TRUE;
    gui_property->props[54].vector_size = 1;

    /* Type specific data: */
    gui_property->props[54].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[54].data.boolean.def   = &jump_to_downloads_def;
    gui_property->props[54].data.boolean.value = &jump_to_downloads;


    /*
     * PROP_SHOW_SEARCH_RESULTS_SETTINGS:
     *
     * General data:
     */
    gui_property->props[55].name = "show_search_results_settings";
    gui_property->props[55].desc = _("Display search settings");
    gui_property->props[55].ev_changed = event_new("show_search_results_settings_changed");
    gui_property->props[55].save = TRUE;
    gui_property->props[55].vector_size = 1;

    /* Type specific data: */
    gui_property->props[55].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[55].data.boolean.def   = &show_search_results_settings_def;
    gui_property->props[55].data.boolean.value = &show_search_results_settings;


    /*
     * PROP_SHOW_DL_SETTINGS:
     *
     * General data:
     */
    gui_property->props[56].name = "show_dl_settings";
    gui_property->props[56].desc = _("Display download settings");
    gui_property->props[56].ev_changed = event_new("show_dl_settings_changed");
    gui_property->props[56].save = TRUE;
    gui_property->props[56].vector_size = 1;

    /* Type specific data: */
    gui_property->props[56].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[56].data.boolean.def   = &show_dl_settings_def;
    gui_property->props[56].data.boolean.value = &show_dl_settings;


    /*
     * PROP_SEARCH_AUTOSELECT_FUZZY:
     *
     * General data:
     */
    gui_property->props[57].name = "search_autoselect_fuzzy";
    gui_property->props[57].desc = _("Use fuzzy name match for autoselection");
    gui_property->props[57].ev_changed = event_new("search_autoselect_fuzzy_changed");
    gui_property->props[57].save = TRUE;
    gui_property->props[57].vector_size = 1;

    /* Type specific data: */
    gui_property->props[57].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[57].data.boolean.def   = &search_autoselect_fuzzy_def;
    gui_property->props[57].data.boolean.value = &search_autoselect_fuzzy;


    /*
     * PROP_SEARCH_STATS_MODE:
     *
     * General data:
     */
    gui_property->props[58].name = "search_stats_mode";
    gui_property->props[58].desc = _("Collect statistics about searches that go through this node");
    gui_property->props[58].ev_changed = event_new("search_stats_mode_changed");
    gui_property->props[58].save = TRUE;
    gui_property->props[58].vector_size = 1;

    /* Type specific data: */
    gui_property->props[58].type               = PROP_TYPE_MULTICHOICE;
    gui_property->props[58].data.guint32.def   = &search_stats_mode_def;
    gui_property->props[58].data.guint32.value = &search_stats_mode;
    gui_property->props[58].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[58].data.guint32.min   = 0x00000000;
    gui_property->props[58].data.guint32.choices = search_stats_mode_choices;


    /*
     * PROP_SEARCH_STATS_UPDATE_INTERVAL:
     *
     * General data:
     */
    gui_property->props[59].name = "search_stats_update_interval";
    gui_property->props[59].desc = _("Interval in which the search stats are updated");
    gui_property->props[59].ev_changed = event_new("search_stats_update_interval_changed");
    gui_property->props[59].save = TRUE;
    gui_property->props[59].vector_size = 1;

    /* Type specific data: */
    gui_property->props[59].type               = PROP_TYPE_GUINT32;
    gui_property->props[59].data.guint32.def   = &search_stats_update_interval_def;
    gui_property->props[59].data.guint32.value = &search_stats_update_interval;
    gui_property->props[59].data.guint32.choices = NULL;
    gui_property->props[59].data.guint32.max   = 50000;
    gui_property->props[59].data.guint32.min   = 0;


    /*
     * PROP_SEARCH_STATS_DELCOEF:
     *
     * General data:
     */
    gui_property->props[60].name = "search_stats_delcoef";
    gui_property->props[60].desc = _("A deletion coefficient, so that small non-significant results can be dropped.  The lower it is, the more search statistics will be kept in memory.");
    gui_property->props[60].ev_changed = event_new("search_stats_delcoef_changed");
    gui_property->props[60].save = TRUE;
    gui_property->props[60].vector_size = 1;

    /* Type specific data: */
    gui_property->props[60].type               = PROP_TYPE_GUINT32;
    gui_property->props[60].data.guint32.def   = &search_stats_delcoef_def;
    gui_property->props[60].data.guint32.value = &search_stats_delcoef;
    gui_property->props[60].data.guint32.choices = NULL;
    gui_property->props[60].data.guint32.max   = 100;
    gui_property->props[60].data.guint32.min   = 0;


    /*
     * PROP_CONFIRM_QUIT:
     *
     * General data:
     */
    gui_property->props[61].name = "confirm_quit";
    gui_property->props[61].desc = _("Show confirmation dialog when leaving gtk-gnutella");
    gui_property->props[61].ev_changed = event_new("confirm_quit_changed");
    gui_property->props[61].save = TRUE;
    gui_property->props[61].vector_size = 1;

    /* Type specific data: */
    gui_property->props[61].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[61].data.boolean.def   = &confirm_quit_def;
    gui_property->props[61].data.boolean.value = &confirm_quit;


    /*
     * PROP_SHOW_TOOLTIPS:
     *
     * General data:
     */
    gui_property->props[62].name = "show_tooltips";
    gui_property->props[62].desc = _("Show a helpful message when the mouse pointer lingers over a widget");
    gui_property->props[62].ev_changed = event_new("show_tooltips_changed");
    gui_property->props[62].save = TRUE;
    gui_property->props[62].vector_size = 1;

    /* Type specific data: */
    gui_property->props[62].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[62].data.boolean.def   = &show_tooltips_def;
    gui_property->props[62].data.boolean.value = &show_tooltips;


    /*
     * PROP_EXPERT_MODE:
     *
     * General data:
     */
    gui_property->props[63].name = "expert_mode";
    gui_property->props[63].desc = _("Show a lot more settings to tweak. If you tamper with them be sure to read up on what they are doing");
    gui_property->props[63].ev_changed = event_new("expert_mode_changed");
    gui_property->props[63].save = TRUE;
    gui_property->props[63].vector_size = 1;

    /* Type specific data: */
    gui_property->props[63].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[63].data.boolean.def   = &expert_mode_def;
    gui_property->props[63].data.boolean.value = &expert_mode;


    /*
     * PROP_GNET_STATS_PERC:
     *
     * General data:
     */
    gui_property->props[64].name = "gnet_stats_perc";
    gui_property->props[64].desc = _("Show percentages instead of absolute values in the gnet stats");
    gui_property->props[64].ev_changed = event_new("gnet_stats_perc_changed");
    gui_property->props[64].save = TRUE;
    gui_property->props[64].vector_size = 1;

    /* Type specific data: */
    gui_property->props[64].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[64].data.boolean.def   = &gnet_stats_perc_def;
    gui_property->props[64].data.boolean.value = &gnet_stats_perc;


    /*
     * PROP_GNET_STATS_BYTES:
     *
     * General data:
     */
    gui_property->props[65].name = "gnet_stats_bytes";
    gui_property->props[65].desc = _("Show bytes instead of packages in the gnet stats");
    gui_property->props[65].ev_changed = event_new("gnet_stats_bytes_changed");
    gui_property->props[65].save = TRUE;
    gui_property->props[65].vector_size = 1;

    /* Type specific data: */
    gui_property->props[65].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[65].data.boolean.def   = &gnet_stats_bytes_def;
    gui_property->props[65].data.boolean.value = &gnet_stats_bytes;


    /*
     * PROP_GNET_STATS_HOPS:
     *
     * General data:
     */
    gui_property->props[66].name = "gnet_stats_hops";
    gui_property->props[66].desc = _("Show stats per hops instead of per TTL");
    gui_property->props[66].ev_changed = event_new("gnet_stats_hops_changed");
    gui_property->props[66].save = TRUE;
    gui_property->props[66].vector_size = 1;

    /* Type specific data: */
    gui_property->props[66].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[66].data.boolean.def   = &gnet_stats_hops_def;
    gui_property->props[66].data.boolean.value = &gnet_stats_hops;


    /*
     * PROP_GNET_STATS_WITH_HEADERS:
     *
     * General data:
     */
    gui_property->props[67].name = "gnet_stats_with_headers";
    gui_property->props[67].desc = _("Add the headers to the volume");
    gui_property->props[67].ev_changed = event_new("gnet_stats_with_headers_changed");
    gui_property->props[67].save = TRUE;
    gui_property->props[67].vector_size = 1;

    /* Type specific data: */
    gui_property->props[67].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[67].data.boolean.def   = &gnet_stats_with_headers_def;
    gui_property->props[67].data.boolean.value = &gnet_stats_with_headers;


    /*
     * PROP_GNET_STATS_DROP_PERC:
     *
     * General data:
     */
    gui_property->props[68].name = "gnet_stats_drop_perc";
    gui_property->props[68].desc = _("Show percentages instead of absolute values in the gnet stats (drop reasons)");
    gui_property->props[68].ev_changed = event_new("gnet_stats_drop_perc_changed");
    gui_property->props[68].save = TRUE;
    gui_property->props[68].vector_size = 1;

    /* Type specific data: */
    gui_property->props[68].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[68].data.boolean.def   = &gnet_stats_drop_perc_def;
    gui_property->props[68].data.boolean.value = &gnet_stats_drop_perc;


    /*
     * PROP_GNET_STATS_GENERAL_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[69].name = "widths_gnet_stats_general";
    gui_property->props[69].desc = _("Widths of the columns in the gnet stats general table");
    gui_property->props[69].ev_changed = event_new("gnet_stats_general_col_widths_changed");
    gui_property->props[69].save = TRUE;
    gui_property->props[69].vector_size = 2;

    /* Type specific data: */
    gui_property->props[69].type               = PROP_TYPE_GUINT32;
    gui_property->props[69].data.guint32.def   = gnet_stats_general_col_widths_def;
    gui_property->props[69].data.guint32.value = gnet_stats_general_col_widths;
    gui_property->props[69].data.guint32.choices = NULL;
    gui_property->props[69].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[69].data.guint32.min   = 0x00000000;


    /*
     * PROP_AUTOCLEAR_COMPLETED_UPLOADS:
     *
     * General data:
     */
    gui_property->props[70].name = "auto_clear_completed_uploads";
    gui_property->props[70].desc = _("Auto clear completed uploads");
    gui_property->props[70].ev_changed = event_new("autoclear_completed_uploads_changed");
    gui_property->props[70].save = TRUE;
    gui_property->props[70].vector_size = 1;

    /* Type specific data: */
    gui_property->props[70].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[70].data.boolean.def   = &clear_uploads_complete_def;
    gui_property->props[70].data.boolean.value = &clear_uploads_complete;


    /*
     * PROP_AUTOCLEAR_FAILED_UPLOADS:
     *
     * General data:
     */
    gui_property->props[71].name = "auto_clear_failed_uploads";
    gui_property->props[71].desc = _("Auto clear failed uploads");
    gui_property->props[71].ev_changed = event_new("autoclear_failed_uploads_changed");
    gui_property->props[71].save = TRUE;
    gui_property->props[71].vector_size = 1;

    /* Type specific data: */
    gui_property->props[71].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[71].data.boolean.def   = &clear_uploads_failed_def;
    gui_property->props[71].data.boolean.value = &clear_uploads_failed;


    /*
     * PROP_NODE_SHOW_UPTIME:
     *
     * General data:
     */
    gui_property->props[72].name = "node_show_uptime";
    gui_property->props[72].desc = _("Whether the node's uptime should be shown (not all nodes provide this information).");
    gui_property->props[72].ev_changed = event_new("node_show_uptime_changed");
    gui_property->props[72].save = TRUE;
    gui_property->props[72].vector_size = 1;

    /* Type specific data: */
    gui_property->props[72].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[72].data.boolean.def   = &node_show_uptime_def;
    gui_property->props[72].data.boolean.value = &node_show_uptime;


    /*
     * PROP_NODE_SHOW_HANDSHAKE_VERSION:
     *
     * General data:
     */
    gui_property->props[73].name = "node_show_handshake_version";
    gui_property->props[73].desc = _("Whether the handshaking version number should be displayed.");
    gui_property->props[73].ev_changed = event_new("node_show_handshake_version_changed");
    gui_property->props[73].save = TRUE;
    gui_property->props[73].vector_size = 1;

    /* Type specific data: */
    gui_property->props[73].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[73].data.boolean.def   = &node_show_handshake_version_def;
    gui_property->props[73].data.boolean.value = &node_show_handshake_version;


    /*
     * PROP_NODE_SHOW_DETAILED_INFO:
     *
     * General data:
     */
    gui_property->props[74].name = "node_show_detailed_info";
    gui_property->props[74].desc = _("Whether detailed traffic information should be shown for the node.  When enabled, it is possible to also customize how much information to display.  When disabled, only TX and RX message counts are displayed, followed by the message queue info.");
    gui_property->props[74].ev_changed = event_new("node_show_detailed_info_changed");
    gui_property->props[74].save = TRUE;
    gui_property->props[74].vector_size = 1;

    /* Type specific data: */
    gui_property->props[74].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[74].data.boolean.def   = &node_show_detailed_info_def;
    gui_property->props[74].data.boolean.value = &node_show_detailed_info;


    /*
     * PROP_SHOW_GNET_INFO_TXC:
     *
     * General data:
     */
    gui_property->props[75].name = "show_gnet_info_txc";
    gui_property->props[75].desc = _("Whether TX traffic compression ratio should be displayed.");
    gui_property->props[75].ev_changed = event_new("show_gnet_info_txc_changed");
    gui_property->props[75].save = TRUE;
    gui_property->props[75].vector_size = 1;

    /* Type specific data: */
    gui_property->props[75].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[75].data.boolean.def   = &show_gnet_info_txc_def;
    gui_property->props[75].data.boolean.value = &show_gnet_info_txc;


    /*
     * PROP_SHOW_GNET_INFO_RXC:
     *
     * General data:
     */
    gui_property->props[76].name = "show_gnet_info_rxc";
    gui_property->props[76].desc = _("Whether RX traffic compression ratio should be displayed.");
    gui_property->props[76].ev_changed = event_new("show_gnet_info_rxc_changed");
    gui_property->props[76].save = TRUE;
    gui_property->props[76].vector_size = 1;

    /* Type specific data: */
    gui_property->props[76].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[76].data.boolean.def   = &show_gnet_info_rxc_def;
    gui_property->props[76].data.boolean.value = &show_gnet_info_rxc;


    /*
     * PROP_SHOW_GNET_INFO_TX_SPEED:
     *
     * General data:
     */
    gui_property->props[77].name = "show_gnet_info_tx_speed";
    gui_property->props[77].desc = _("Whether TX instantaneous transmission speed should be displayed.");
    gui_property->props[77].ev_changed = event_new("show_gnet_info_tx_speed_changed");
    gui_property->props[77].save = TRUE;
    gui_property->props[77].vector_size = 1;

    /* Type specific data: */
    gui_property->props[77].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[77].data.boolean.def   = &show_gnet_info_tx_speed_def;
    gui_property->props[77].data.boolean.value = &show_gnet_info_tx_speed;


    /*
     * PROP_SHOW_GNET_INFO_RX_SPEED:
     *
     * General data:
     */
    gui_property->props[78].name = "show_gnet_info_rx_speed";
    gui_property->props[78].desc = _("Whether RX instantaneous transmission speed should be displayed.");
    gui_property->props[78].ev_changed = event_new("show_gnet_info_rx_speed_changed");
    gui_property->props[78].save = TRUE;
    gui_property->props[78].vector_size = 1;

    /* Type specific data: */
    gui_property->props[78].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[78].data.boolean.def   = &show_gnet_info_rx_speed_def;
    gui_property->props[78].data.boolean.value = &show_gnet_info_rx_speed;


    /*
     * PROP_SHOW_GNET_INFO_TX_QUERIES:
     *
     * General data:
     */
    gui_property->props[79].name = "show_gnet_info_tx_queries";
    gui_property->props[79].desc = _("Whether count of transmitted queries should be displayed.");
    gui_property->props[79].ev_changed = event_new("show_gnet_info_tx_queries_changed");
    gui_property->props[79].save = TRUE;
    gui_property->props[79].vector_size = 1;

    /* Type specific data: */
    gui_property->props[79].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[79].data.boolean.def   = &show_gnet_info_tx_queries_def;
    gui_property->props[79].data.boolean.value = &show_gnet_info_tx_queries;


    /*
     * PROP_SHOW_GNET_INFO_RX_QUERIES:
     *
     * General data:
     */
    gui_property->props[80].name = "show_gnet_info_rx_queries";
    gui_property->props[80].desc = _("Whether count of received queries should be displayed.");
    gui_property->props[80].ev_changed = event_new("show_gnet_info_rx_queries_changed");
    gui_property->props[80].save = TRUE;
    gui_property->props[80].vector_size = 1;

    /* Type specific data: */
    gui_property->props[80].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[80].data.boolean.def   = &show_gnet_info_rx_queries_def;
    gui_property->props[80].data.boolean.value = &show_gnet_info_rx_queries;


    /*
     * PROP_SHOW_GNET_INFO_TX_HITS:
     *
     * General data:
     */
    gui_property->props[81].name = "show_gnet_info_tx_hits";
    gui_property->props[81].desc = _("Whether count of transmitted query hits should be displayed.");
    gui_property->props[81].ev_changed = event_new("show_gnet_info_tx_hits_changed");
    gui_property->props[81].save = TRUE;
    gui_property->props[81].vector_size = 1;

    /* Type specific data: */
    gui_property->props[81].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[81].data.boolean.def   = &show_gnet_info_tx_hits_def;
    gui_property->props[81].data.boolean.value = &show_gnet_info_tx_hits;


    /*
     * PROP_SHOW_GNET_INFO_RX_HITS:
     *
     * General data:
     */
    gui_property->props[82].name = "show_gnet_info_rx_hits";
    gui_property->props[82].desc = _("Whether count of received query hits should be displayed.");
    gui_property->props[82].ev_changed = event_new("show_gnet_info_rx_hits_changed");
    gui_property->props[82].save = TRUE;
    gui_property->props[82].vector_size = 1;

    /* Type specific data: */
    gui_property->props[82].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[82].data.boolean.def   = &show_gnet_info_rx_hits_def;
    gui_property->props[82].data.boolean.value = &show_gnet_info_rx_hits;


    /*
     * PROP_SHOW_GNET_INFO_GEN_QUERIES:
     *
     * General data:
     */
    gui_property->props[83].name = "show_gnet_info_gen_queries";
    gui_property->props[83].desc = _("Whether count of locally generated queries should be displayed.");
    gui_property->props[83].ev_changed = event_new("show_gnet_info_gen_queries_changed");
    gui_property->props[83].save = TRUE;
    gui_property->props[83].vector_size = 1;

    /* Type specific data: */
    gui_property->props[83].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[83].data.boolean.def   = &show_gnet_info_gen_queries_def;
    gui_property->props[83].data.boolean.value = &show_gnet_info_gen_queries;


    /*
     * PROP_SHOW_GNET_INFO_SQ_QUERIES:
     *
     * General data:
     */
    gui_property->props[84].name = "show_gnet_info_sq_queries";
    gui_property->props[84].desc = _("Whether count of local queries pending transmission should be displayed.");
    gui_property->props[84].ev_changed = event_new("show_gnet_info_sq_queries_changed");
    gui_property->props[84].save = TRUE;
    gui_property->props[84].vector_size = 1;

    /* Type specific data: */
    gui_property->props[84].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[84].data.boolean.def   = &show_gnet_info_sq_queries_def;
    gui_property->props[84].data.boolean.value = &show_gnet_info_sq_queries;


    /*
     * PROP_SHOW_GNET_INFO_TX_DROPPED:
     *
     * General data:
     */
    gui_property->props[85].name = "show_gnet_info_tx_dropped";
    gui_property->props[85].desc = _("Whether count of dropped messages on TX should be displayed.");
    gui_property->props[85].ev_changed = event_new("show_gnet_info_tx_dropped_changed");
    gui_property->props[85].save = TRUE;
    gui_property->props[85].vector_size = 1;

    /* Type specific data: */
    gui_property->props[85].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[85].data.boolean.def   = &show_gnet_info_tx_dropped_def;
    gui_property->props[85].data.boolean.value = &show_gnet_info_tx_dropped;


    /*
     * PROP_SHOW_GNET_INFO_RX_DROPPED:
     *
     * General data:
     */
    gui_property->props[86].name = "show_gnet_info_rx_dropped";
    gui_property->props[86].desc = _("Whether count of dropped messages on RX should be displayed.");
    gui_property->props[86].ev_changed = event_new("show_gnet_info_rx_dropped_changed");
    gui_property->props[86].save = TRUE;
    gui_property->props[86].vector_size = 1;

    /* Type specific data: */
    gui_property->props[86].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[86].data.boolean.def   = &show_gnet_info_rx_dropped_def;
    gui_property->props[86].data.boolean.value = &show_gnet_info_rx_dropped;


    /*
     * PROP_SHOW_GNET_INFO_QRP_STATS:
     *
     * General data:
     */
    gui_property->props[87].name = "show_gnet_info_qrp_stats";
    gui_property->props[87].desc = _("Whether Query Routing Protocol statistics should be displayed. For a leaf node, this is simply the ratio of queries that generated a hit over the amount of received queries.  For an ultrapeer, it displays the amount of slots in the QRP table, 'g' the generation number, 'f' the fill ratio, 't' the passing threshold and 'e' the efficiency, i.e. the proportion of received queries that are sent to the leaf.");
    gui_property->props[87].ev_changed = event_new("show_gnet_info_qrp_stats_changed");
    gui_property->props[87].save = TRUE;
    gui_property->props[87].vector_size = 1;

    /* Type specific data: */
    gui_property->props[87].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[87].data.boolean.def   = &show_gnet_info_qrp_stats_def;
    gui_property->props[87].data.boolean.value = &show_gnet_info_qrp_stats;


    /*
     * PROP_SHOW_GNET_INFO_DBW:
     *
     * General data:
     */
    gui_property->props[88].name = "show_gnet_info_dbw";
    gui_property->props[88].desc = _("Whether duplicate, bad and weird received message counts should be displayed.");
    gui_property->props[88].ev_changed = event_new("show_gnet_info_dbw_changed");
    gui_property->props[88].save = TRUE;
    gui_property->props[88].vector_size = 1;

    /* Type specific data: */
    gui_property->props[88].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[88].data.boolean.def   = &show_gnet_info_dbw_def;
    gui_property->props[88].data.boolean.value = &show_gnet_info_dbw;


    /*
     * PROP_SHOW_GNET_INFO_RT:
     *
     * General data:
     */
    gui_property->props[89].name = "show_gnet_info_rt";
    gui_property->props[89].desc = _("Whether ping/pong roundtrip times (average and last) should be displayed.  Values shown are in milliseconds.");
    gui_property->props[89].ev_changed = event_new("show_gnet_info_rt_changed");
    gui_property->props[89].save = TRUE;
    gui_property->props[89].vector_size = 1;

    /* Type specific data: */
    gui_property->props[89].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[89].data.boolean.def   = &show_gnet_info_rt_def;
    gui_property->props[89].data.boolean.value = &show_gnet_info_rt;


    /*
     * PROP_SHOW_GNET_INFO_SHARED_SIZE:
     *
     * General data:
     */
    gui_property->props[90].name = "show_gnet_info_shared_size";
    gui_property->props[90].desc = _("Whether we should display the size of the node's library, when it is known to us.");
    gui_property->props[90].ev_changed = event_new("show_gnet_info_shared_size_changed");
    gui_property->props[90].save = TRUE;
    gui_property->props[90].vector_size = 1;

    /* Type specific data: */
    gui_property->props[90].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[90].data.boolean.def   = &show_gnet_info_shared_size_def;
    gui_property->props[90].data.boolean.value = &show_gnet_info_shared_size;


    /*
     * PROP_SHOW_GNET_INFO_SHARED_FILES:
     *
     * General data:
     */
    gui_property->props[91].name = "show_gnet_info_shared_files";
    gui_property->props[91].desc = _("Whether we should display the amount of files shared by nodes, when that is known to us.");
    gui_property->props[91].ev_changed = event_new("show_gnet_info_shared_files_changed");
    gui_property->props[91].save = TRUE;
    gui_property->props[91].vector_size = 1;

    /* Type specific data: */
    gui_property->props[91].type               = PROP_TYPE_BOOLEAN;
    gui_property->props[91].data.boolean.def   = &show_gnet_info_shared_files_def;
    gui_property->props[91].data.boolean.value = &show_gnet_info_shared_files;


    /*
     * PROP_SEARCH_ACCUMULATION_PERIOD:
     *
     * General data:
     */
    gui_property->props[92].name = "search_accumulation_period";
    gui_property->props[92].desc = _("The amount of time in seconds that the GUI should buffer search results as they come in.  This prevents too frequent updates that may cause flickering, but also saves CPU cycles since less redrawing has to occur in the search pane.");
    gui_property->props[92].ev_changed = event_new("search_accumulation_period_changed");
    gui_property->props[92].save = TRUE;
    gui_property->props[92].vector_size = 1;

    /* Type specific data: */
    gui_property->props[92].type               = PROP_TYPE_GUINT32;
    gui_property->props[92].data.guint32.def   = &search_accumulation_period_def;
    gui_property->props[92].data.guint32.value = &search_accumulation_period;
    gui_property->props[92].data.guint32.choices = NULL;
    gui_property->props[92].data.guint32.max   = 30;
    gui_property->props[92].data.guint32.min   = 1;


    /*
     * PROP_TREEMENU_NODES_EXPANDED:
     *
     * General data:
     */
    gui_property->props[93].name = "treemenu_nodes_expanded";
    gui_property->props[93].desc = _("Expanded stati of the nodes in the treemenu");
    gui_property->props[93].ev_changed = event_new("treemenu_nodes_expanded_changed");
    gui_property->props[93].save = TRUE;
    gui_property->props[93].vector_size = 16;

    /* Type specific data: */
    gui_property->props[93].type               = PROP_TYPE_GUINT32;
    gui_property->props[93].data.guint32.def   = treemenu_nodes_expanded_def;
    gui_property->props[93].data.guint32.value = treemenu_nodes_expanded;
    gui_property->props[93].data.guint32.choices = NULL;
    gui_property->props[93].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[93].data.guint32.min   = 0x00000000;


    /*
     * PROP_GNET_STATS_PKG_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[94].name = "widths_gnet_stats_pkg";
    gui_property->props[94].desc = _("Widths of the columns in the gnet packet stats table (pkg)[GTK2]");
    gui_property->props[94].ev_changed = event_new("gnet_stats_pkg_col_widths_changed");
    gui_property->props[94].save = TRUE;
    gui_property->props[94].vector_size = 6;

    /* Type specific data: */
    gui_property->props[94].type               = PROP_TYPE_GUINT32;
    gui_property->props[94].data.guint32.def   = gnet_stats_pkg_col_widths_def;
    gui_property->props[94].data.guint32.value = gnet_stats_pkg_col_widths;
    gui_property->props[94].data.guint32.choices = NULL;
    gui_property->props[94].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[94].data.guint32.min   = 0x00000000;


    /*
     * PROP_GNET_STATS_BYTE_COL_WIDTHS:
     *
     * General data:
     */
    gui_property->props[95].name = "widths_gnet_stats_byte";
    gui_property->props[95].desc = _("Widths of the columns in the gnet packet stats table (byte) [GTK2]");
    gui_property->props[95].ev_changed = event_new("gnet_stats_byte_col_widths_changed");
    gui_property->props[95].save = TRUE;
    gui_property->props[95].vector_size = 6;

    /* Type specific data: */
    gui_property->props[95].type               = PROP_TYPE_GUINT32;
    gui_property->props[95].data.guint32.def   = gnet_stats_byte_col_widths_def;
    gui_property->props[95].data.guint32.value = gnet_stats_byte_col_widths;
    gui_property->props[95].data.guint32.choices = NULL;
    gui_property->props[95].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[95].data.guint32.min   = 0x00000000;


    /*
     * PROP_CONFIG_TOOLBAR_STYLE:
     *
     * General data:
     */
    gui_property->props[96].name = "config_toolbar_style";
    gui_property->props[96].desc = _("Configures the appearance of the toolbar");
    gui_property->props[96].ev_changed = event_new("config_toolbar_style_changed");
    gui_property->props[96].save = TRUE;
    gui_property->props[96].vector_size = 1;

    /* Type specific data: */
    gui_property->props[96].type               = PROP_TYPE_MULTICHOICE;
    gui_property->props[96].data.guint32.def   = &config_toolbar_style_def;
    gui_property->props[96].data.guint32.value = &config_toolbar_style;
    gui_property->props[96].data.guint32.max   = 0xFFFFFFFF;
    gui_property->props[96].data.guint32.min   = 0x00000000;
    gui_property->props[96].data.guint32.choices = config_toolbar_style_choices;

    gui_property->byName = g_hash_table_new(g_str_hash, g_str_equal);
    for (n = 0; n < GUI_PROPERTY_NUM; n ++) {
        g_hash_table_insert(gui_property->byName, 
            gui_property->props[n].name, GINT_TO_POINTER(n+1000));
    }

    return gui_property;
}

/*
 * gui_prop_shutdown:
 *
 * Free memory allocated by the property set.
 */
void gui_prop_shutdown(void) {
    gint n;

    if (gui_property->byName) {
        g_hash_table_destroy(gui_property->byName);
        gui_property->byName = NULL;
    }

    for (n = 0; n < GUI_PROPERTY_NUM; n ++) {
        if (gui_property->props[n].type == PROP_TYPE_STRING) {
			gchar **p = gui_property->props[n].data.string.value;
            struct event *e = gui_property->props[n].ev_changed;
			if (*p)
				G_FREE_NULL(*p);
            if (e)
                event_destroy(e);    
        }
    }

    G_FREE_NULL(gui_property->props);
    G_FREE_NULL(gui_property);
}

prop_def_t *gui_prop_get_def(property_t p)
{
    return prop_get_def(gui_property, p);
}

/*
 * gui_prop_add_prop_changed_listener:
 *
 * Add a change listener to a given property. If init is TRUE then
 * the listener is immediately called.
 */
void gui_prop_add_prop_changed_listener(
    property_t prop, prop_changed_listener_t l, gboolean init)
{
    prop_add_prop_changed_listener(gui_property, prop, l, init);
}

/*
 * gui_prop_add_prop_changed_listener_full:
 *
 * Add a change listener to a given property. If init is TRUE then
 * the listener is immediately called. 
 */
void gui_prop_add_prop_changed_listener_full(
    property_t prop, prop_changed_listener_t l, gboolean init, 
    enum frequency_type freq, guint32 interval)
{
    prop_add_prop_changed_listener_full(gui_property, prop, l, init,
        freq, interval);
}

void gui_prop_remove_prop_changed_listener(
    property_t prop, prop_changed_listener_t l)
{
    prop_remove_prop_changed_listener(gui_property, prop, l);
}

void gui_prop_set_boolean(
    property_t prop, const gboolean *src, gsize offset, gsize length)
{
    prop_set_boolean(gui_property, prop, src, offset, length);
}

gboolean *gui_prop_get_boolean(
    property_t prop, gboolean *t, gsize offset, gsize length)
{
    return prop_get_boolean(gui_property, prop, t, offset, length);
}

void gui_prop_set_guint32(
    property_t prop, const guint32 *src, gsize offset, gsize length)
{
    prop_set_guint32(gui_property, prop, src, offset, length);
}

guint32 *gui_prop_get_guint32(
    property_t prop, guint32 *t, gsize offset, gsize length)
{
    return prop_get_guint32(gui_property, prop, t, offset, length);
}

void gui_prop_set_guint64(
    property_t prop, const guint64 *src, gsize offset, gsize length)
{
    prop_set_guint64(gui_property, prop, src, offset, length);
}

guint64 *gui_prop_get_guint64(
    property_t prop, guint64 *t, gsize offset, gsize length)
{
    return prop_get_guint64(gui_property, prop, t, offset, length);
}

void gui_prop_set_string(property_t prop, const gchar *val)
{
    prop_set_string(gui_property, prop, val);
}

gchar *gui_prop_get_string(property_t prop, gchar *t, gsize size)
{
    return prop_get_string(gui_property, prop, t, size);
}

void gui_prop_set_storage(property_t p, const guint8 *v, gsize l)
{
    prop_set_storage(gui_property, p, v, l);
}

guint8 *gui_prop_get_storage(property_t p, guint8 *t, gsize l)
{
    return prop_get_storage(gui_property, p, t, l);
}

gchar *gui_prop_to_string(property_t prop)
{
    return prop_to_string(gui_property, prop);
}

gchar *gui_prop_name(property_t p)
{
    return prop_name(gui_property, p);
}

property_t gui_prop_get_by_name(const gchar *name)
{
    return GPOINTER_TO_UINT(
        g_hash_table_lookup(gui_property->byName, name));
}


/*
 * gui_prop_get_stub:
 *
 * Returns a new stub struct for this property set. Just g_free it
 * when it is no longer needed. All fields are read only!
 */
prop_set_stub_t *gui_prop_get_stub(void) 
{
    prop_set_stub_t *stub;

    stub          = g_new0(prop_set_stub_t, 1);
    stub->size    = GUI_PROPERTY_NUM;
    stub->offset  = GUI_PROPERTY_MIN;
    stub->get_def = gui_prop_get_def;
    stub->get_by_name = gui_prop_get_by_name;
    stub->to_string = gui_prop_to_string;

    stub->prop_changed_listener.add = 
        gui_prop_add_prop_changed_listener;
    stub->prop_changed_listener.add_full = 
        gui_prop_add_prop_changed_listener_full;
    stub->prop_changed_listener.remove = 
        gui_prop_remove_prop_changed_listener;

    stub->boolean.get = gui_prop_get_boolean;
    stub->boolean.set = gui_prop_set_boolean;

    stub->guint32.get = gui_prop_get_guint32;
    stub->guint32.set = gui_prop_set_guint32;

    stub->guint64.get = gui_prop_get_guint64;
    stub->guint64.set = gui_prop_set_guint64;

    stub->string.get = gui_prop_get_string;
    stub->string.set = gui_prop_set_string;

    stub->storage.get = gui_prop_get_storage;
    stub->storage.set = gui_prop_set_storage;

    return stub;
}
