/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_popup_dl_active (void);
GtkWidget* create_popup_dl_queued (void);
GtkWidget* create_popup_hosts (void);
GtkWidget* create_popup_search (void);
GtkWidget* create_popup_monitor (void);
GtkWidget* create_popup_nodes (void);
GtkWidget* create_popup_uploads (void);

/* Global Widgets (added by extern.tcl) */

extern GtkWidget *notebook_main;
extern GtkWidget *clist_menu;
extern GtkWidget *clist_stats;
extern GtkWidget *clist_connections;
extern GtkWidget *button_stats_update;
extern GtkWidget *clist_nodes;
extern GtkWidget *button_nodes_add;
extern GtkWidget *button_nodes_remove;
extern GtkWidget *entry_host;
extern GtkWidget *entry_up_connections;
extern GtkWidget *entry_global_messages;
extern GtkWidget *entry_global_searches;
extern GtkWidget *entry_routing_errors;
extern GtkWidget *entry_dropped_messages;
extern GtkWidget *entry_count_downloads;
extern GtkWidget *entry_count_uploads;
extern GtkWidget *clist_host_catcher;
extern GtkWidget *button_host_catcher_connect;
extern GtkWidget *button_host_catcher_get_more;
extern GtkWidget *button_host_catcher_remove;
extern GtkWidget *button_host_catcher_clear;
extern GtkWidget *clist_uploads;
extern GtkWidget *button_kill_upload;
extern GtkWidget *button_clear_uploads;
extern GtkWidget *checkbutton_clear_uploads;
extern GtkWidget *clist_downloads;
extern GtkWidget *button_abort_download;
extern GtkWidget *button_resume_download;
extern GtkWidget *button_clear_download;
extern GtkWidget *entry_max_downloads;
extern GtkWidget *checkbutton_clear_downloads;
extern GtkWidget *clist_download_queue;
extern GtkWidget *button_remove_download;
extern GtkWidget *entry_search;
extern GtkWidget *button_search;
extern GtkWidget *label_items_found;
extern GtkWidget *entry_minimum_speed;
extern GtkWidget *notebook_search_results;
extern GtkWidget *button_search_download;
extern GtkWidget *button_search_stream;
extern GtkWidget *combo_searches;
extern GtkWidget *combo_entry_searches;
extern GtkWidget *button_search_filter;
extern GtkWidget *button_search_close;
extern GtkWidget *checkbutton_monitor;
extern GtkWidget *entry_monitor;
extern GtkWidget *clist_monitor;
extern GtkWidget *button_config_move_path;
extern GtkWidget *button_config_save_path;
extern GtkWidget *entry_config_path;
extern GtkWidget *label_files_scanned;
extern GtkWidget *entry_config_extensions;
extern GtkWidget *entry_config_port;
extern GtkWidget *entry_config_force_ip;
extern GtkWidget *entry_config_speed;
extern GtkWidget *checkbutton_config_throttle;
extern GtkWidget *label_current_port;
extern GtkWidget *checkbutton_config_force_ip;
extern GtkWidget *entry_config_search_items;
extern GtkWidget *entry_config_maxttl;
extern GtkWidget *entry_config_myttl;
extern GtkWidget *button_config_update_port;
extern GtkWidget *button_config_rescan_dir;
extern GtkWidget *label_left;
extern GtkWidget *label_right;
extern GtkWidget *popup_hosts;
extern GtkWidget *popup_hosts_title;
extern GtkWidget *popup_hosts_export;
extern GtkWidget *popup_dl_active;
extern GtkWidget *popup_dl_active_title;
extern GtkWidget *download_p_push;
extern GtkWidget *download_p_queue;
extern GtkWidget *download_p_kill;
extern GtkWidget *popup_dl_queued;
extern GtkWidget *popup_dl_queued_title;
extern GtkWidget *download_start_now;
extern GtkWidget *popup_search;
extern GtkWidget *popup_search_title;
extern GtkWidget *popup_search_stop_sorting;
extern GtkWidget *popup_search_filters;
extern GtkWidget *popup_search_close;
extern GtkWidget *popup_search_toggle_tabs;
extern GtkWidget *popup_monitor;
extern GtkWidget *popup_monitor_title;
extern GtkWidget *popup_nodes;
extern GtkWidget *popup_nodes_title;
extern GtkWidget *popup_uploads;
extern GtkWidget *popup_uploads_title;

/* End of global widgets */

