name: gtk-gnutella
version: '1.1.14'
summary: The Most Efficient Gnutella Client
description: |
    gtk-gnutella is a server/client for the Gnutella peer-to-peer network.
    It runs on Microsoft Windows, MacOS and every Unix-like system which supports GTK+ (1.2 or above)

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
    
parts:
  gtk-gnutella:
    plugin: autotools
    override-build: ./build.sh
    source-type: git
    source: https://github.com/gtk-gnutella/gtk-gnutella.git

    build-packages:
      - g++
      - make
      - libsdl1.2-dev
      - libpng12-dev
      - libsdl-net1.2-dev
      - libsdl-sound1.2-dev
      - libasound2-dev
      - libgtk2.0-dev
